import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const ANIMALS_VOCABULARY: ButtonTemplate[] = [
  // Domestic Animals
  {
    id: "dog",
    text: "Dog",
    message: "I see a dog.",
    twoWord: "See dog",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("dog"),
  },
  {
    id: "cat",
    text: "Cat",
    message: "I see a cat.",
    twoWord: "See cat",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("cat"),
  },
  {
    id: "bird",
    text: "Bird",
    message: "I see a bird.",
    twoWord: "See bird",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("bird"),
  },
  {
    id: "fish-animal",
    text: "Fish",
    message: "I see a fish.",
    twoWord: "See fish",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("fish"),
  },
  {
    id: "horse",
    text: "Horse",
    message: "I see a horse.",
    twoWord: "See horse",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("horse"),
  },
  {
    id: "cow",
    text: "Cow",
    message: "I see a cow.",
    twoWord: "See cow",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("cow"),
  },
  {
    id: "sheep",
    text: "Sheep",
    message: "I see a sheep.",
    twoWord: "See sheep",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("sheep"),
  },
  {
    id: "pig",
    text: "Pig",
    message: "I see a pig.",
    twoWord: "See pig",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("pig"),
  },
  {
    id: "chicken-animal",
    text: "Chicken",
    message: "I see a chicken.",
    twoWord: "See chicken",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("chicken-animal"),
  },
  {
    id: "duck",
    text: "Duck",
    message: "I see a duck.",
    twoWord: "See duck",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("duck"),
  },
  {
    id: "rabbit",
    text: "Rabbit",
    message: "I see a rabbit.",
    twoWord: "See rabbit",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("rabbit"),
  },
  // Wild Animals
  {
    id: "lion",
    text: "Lion",
    message: "I see a lion.",
    twoWord: "See lion",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("lion"),
  },
  {
    id: "tiger",
    text: "Tiger",
    message: "I see a tiger.",
    twoWord: "See tiger",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("tiger"),
  },
  {
    id: "elephant",
    text: "Elephant",
    message: "I see an elephant.",
    twoWord: "See elephant",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("elephant"),
  },
  {
    id: "monkey",
    text: "Monkey",
    message: "I see a monkey.",
    twoWord: "See monkey",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("monkey"),
  },
  {
    id: "bear",
    text: "Bear",
    message: "I see a bear.",
    twoWord: "See bear",
    category: "animals",
    color: "#8E44AD",
    translations: getTranslationsForWord("bear"),
  },
];
