import { ButtonTemplate } from "../../types";

export const ANIMALS_VOCABULARY: ButtonTemplate[] = [
  // Domestic Animals
  {
    id: "dog",
    text: "Dog",
    message: "I see a dog.",
    twoWord: "See dog",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Dog",
      hi: "कुत्ता",
      es: "Perro",
      fr: "Chien",
      zh: "狗",
    },
  },
  {
    id: "cat",
    text: "Cat",
    message: "I see a cat.",
    twoWord: "See cat",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Cat",
      hi: "बिल्ली",
      es: "Gato",
      fr: "Chat",
      zh: "猫",
    },
  },
  {
    id: "bird",
    text: "Bird",
    message: "I see a bird.",
    twoWord: "See bird",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Bird",
      hi: "पक्षी",
      es: "Pájaro",
      fr: "Oiseau",
      zh: "鸟",
    },
  },
  {
    id: "fish",
    text: "Fish",
    message: "I see a fish.",
    twoWord: "See fish",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Fish",
      hi: "मछली",
      es: "Pez",
      fr: "Poisson",
      zh: "鱼",
    },
  },
  {
    id: "horse",
    text: "Horse",
    message: "I see a horse.",
    twoWord: "See horse",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Horse",
      hi: "घोड़ा",
      es: "Caballo",
      fr: "Cheval",
      zh: "马",
    },
  },
  {
    id: "cow",
    text: "Cow",
    message: "I see a cow.",
    twoWord: "See cow",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Cow",
      hi: "गाय",
      es: "Vaca",
      fr: "Vache",
      zh: "牛",
    },
  },
  {
    id: "sheep",
    text: "Sheep",
    message: "I see a sheep.",
    twoWord: "See sheep",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Sheep",
      hi: "भेड़",
      es: "Oveja",
      fr: "Mouton",
      zh: "羊",
    },
  },
  {
    id: "pig",
    text: "Pig",
    message: "I see a pig.",
    twoWord: "See pig",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Pig",
      hi: "सूअर",
      es: "Cerdo",
      fr: "Cochon",
      zh: "猪",
    },
  },
  {
    id: "chicken",
    text: "Chicken",
    message: "I see a chicken.",
    twoWord: "See chicken",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Chicken",
      hi: "मुर्गी",
      es: "Pollo",
      fr: "Poule",
      zh: "鸡",
    },
  },
  {
    id: "duck",
    text: "Duck",
    message: "I see a duck.",
    twoWord: "See duck",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Duck",
      hi: "बतख",
      es: "Pato",
      fr: "Canard",
      zh: "鸭子",
    },
  },
  {
    id: "rabbit",
    text: "Rabbit",
    message: "I see a rabbit.",
    twoWord: "See rabbit",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Rabbit",
      hi: "खरगोश",
      es: "Conejo",
      fr: "Lapin",
      zh: "兔子",
    },
  },
  // Wild Animals
  {
    id: "lion",
    text: "Lion",
    message: "I see a lion.",
    twoWord: "See lion",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Lion",
      hi: "शेर",
      es: "León",
      fr: "Lion",
      zh: "狮子",
    },
  },
  {
    id: "tiger",
    text: "Tiger",
    message: "I see a tiger.",
    twoWord: "See tiger",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Tiger",
      hi: "बाघ",
      es: "Tigre",
      fr: "Tigre",
      zh: "老虎",
    },
  },
  {
    id: "elephant",
    text: "Elephant",
    message: "I see an elephant.",
    twoWord: "See elephant",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Elephant",
      hi: "हाथी",
      es: "Elefante",
      fr: "Éléphant",
      zh: "大象",
    },
  },
  {
    id: "monkey",
    text: "Monkey",
    message: "I see a monkey.",
    twoWord: "See monkey",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Monkey",
      hi: "बंदर",
      es: "Mono",
      fr: "Singe",
      zh: "猴子",
    },
  },
  {
    id: "bear",
    text: "Bear",
    message: "I see a bear.",
    twoWord: "See bear",
    category: "animals",
    color: "#8E44AD",
    translations: {
      en: "Bear",
      hi: "भालू",
      es: "Oso",
      fr: "Ours",
      zh: "熊",
    },
  },
];
