import { ButtonTemplate } from "../../types";

export const BATHROOM_VOCABULARY: ButtonTemplate[] = [
  // Fixtures
  {
    id: "toilet",
    text: "Toilet",
    message: "I need to use the toilet.",
    twoWord: "Want toilet",
    category: "bathroom",
    subCategory: "fixtures",
    color: "#45B7D1",
    translations: {
      en: "Toilet",
      hi: "शौचालय",
      es: "Baño",
      fr: "Toilettes",
      zh: "厕所",
    },
  },
  {
    id: "sink",
    text: "Sink",
    message: "I want to wash my hands.",
    twoWord: "Want sink",
    category: "bathroom",
    subCategory: "fixtures",
    color: "#45B7D1",
    translations: {
      en: "Sink",
      hi: "सिंक",
      es: "Lavabo",
      fr: "Lavabo",
      zh: "水槽",
    },
  },
  {
    id: "shower",
    text: "Shower",
    message: "I want to take a shower.",
    twoWord: "Want shower",
    category: "bathroom",
    subCategory: "fixtures",
    color: "#45B7D1",
    translations: {
      en: "Shower",
      hi: "शॉवर",
      es: "Ducha",
      fr: "Douche",
      zh: "淋浴",
    },
  },
  {
    id: "bath",
    text: "Bath",
    message: "I want to take a bath.",
    twoWord: "Want bath",
    category: "bathroom",
    subCategory: "fixtures",
    color: "#45B7D1",
    translations: {
      en: "Bath",
      hi: "स्नान",
      es: "Baño",
      fr: "Bain",
      zh: "浴缸",
    },
  },

  // Hygiene
  {
    id: "soap",
    text: "Soap",
    message: "I want soap.",
    twoWord: "Want soap",
    category: "bathroom",
    subCategory: "hygiene",
    color: "#45B7D1",
    translations: {
      en: "Soap",
      hi: "साबुन",
      es: "Jabón",
      fr: "Savon",
      zh: "肥皂",
    },
  },
  {
    id: "towel",
    text: "Towel",
    message: "I want a towel.",
    twoWord: "Want towel",
    category: "bathroom",
    subCategory: "hygiene",
    color: "#45B7D1",
    translations: {
      en: "Towel",
      hi: "तौलिया",
      es: "Toalla",
      fr: "Serviette",
      zh: "毛巾",
    },
  },
  {
    id: "toothbrush",
    text: "Toothbrush",
    message: "I want to brush my teeth.",
    twoWord: "Want toothbrush",
    category: "bathroom",
    subCategory: "hygiene",
    color: "#45B7D1",
    translations: {
      en: "Toothbrush",
      hi: "टूथब्रश",
      es: "Cepillo de dientes",
      fr: "Brosse à dents",
      zh: "牙刷",
    },
  },
  {
    id: "toothpaste",
    text: "Toothpaste",
    message: "I want toothpaste.",
    twoWord: "Want toothpaste",
    category: "bathroom",
    subCategory: "hygiene",
    color: "#45B7D1",
    translations: {
      en: "Toothpaste",
      hi: "टूथपेस्ट",
      es: "Pasta de dientes",
      fr: "Dentifrice",
      zh: "牙膏",
    },
  },
];
