import { ButtonTemplate } from "../../types";

export const CLOTHING_VOCABULARY: ButtonTemplate[] = [
  // Tops
  {
    id: "shirt",
    text: "Shirt",
    message: "I want to wear a shirt.",
    twoWord: "Want shirt",
    category: "clothing",
    subCategory: "tops",
    color: "#9B59B6",
    translations: {
      en: "Shirt",
      hi: "शर्ट",
      es: "Camisa",
      fr: "Chemise",
      zh: "衬衫",
    },
  },
  {
    id: "dress",
    text: "Dress",
    message: "I want to wear a dress.",
    twoWord: "Want dress",
    category: "clothing",
    subCategory: "tops",
    color: "#9B59B6",
    translations: {
      en: "Dress",
      hi: "ड्रेस",
      es: "Vestido",
      fr: "Robe",
      zh: "连衣裙",
    },
  },
  {
    id: "jacket",
    text: "Jacket",
    message: "I want to wear a jacket.",
    twoWord: "Want jacket",
    category: "clothing",
    subCategory: "tops",
    color: "#9B59B6",
    translations: {
      en: "Jacket",
      hi: "जैकेट",
      es: "Chaqueta",
      fr: "Veste",
      zh: "夹克",
    },
  },
  {
    id: "coat",
    text: "Coat",
    message: "I want to wear a coat.",
    twoWord: "Want coat",
    category: "clothing",
    subCategory: "tops",
    color: "#9B59B6",
    translations: {
      en: "Coat",
      hi: "कोट",
      es: "Abrigo",
      fr: "Manteau",
      zh: "外套",
    },
  },

  // Bottoms
  {
    id: "pants",
    text: "Pants",
    message: "I want to wear pants.",
    twoWord: "Want pants",
    category: "clothing",
    subCategory: "bottoms",
    color: "#9B59B6",
    translations: {
      en: "Pants",
      hi: "पैंट",
      es: "Pantalones",
      fr: "Pantalon",
      zh: "裤子",
    },
  },

  // Accessories
  {
    id: "shoes",
    text: "Shoes",
    message: "I want to wear shoes.",
    twoWord: "Want shoes",
    category: "clothing",
    subCategory: "accessories",
    color: "#9B59B6",
    translations: {
      en: "Shoes",
      hi: "जूते",
      es: "Zapatos",
      fr: "Chaussures",
      zh: "鞋子",
    },
  },
  {
    id: "socks",
    text: "Socks",
    message: "I want to wear socks.",
    twoWord: "Want socks",
    category: "clothing",
    subCategory: "accessories",
    color: "#9B59B6",
    translations: {
      en: "Socks",
      hi: "मोज़े",
      es: "Calcetines",
      fr: "Chaussettes",
      zh: "袜子",
    },
  },
  {
    id: "hat",
    text: "Hat",
    message: "I want to wear a hat.",
    twoWord: "Want hat",
    category: "clothing",
    subCategory: "accessories",
    color: "#9B59B6",
    translations: {
      en: "Hat",
      hi: "टोपी",
      es: "Sombrero",
      fr: "Chapeau",
      zh: "帽子",
    },
  },
];
