import { ButtonTemplate } from "../../types";

export const COLORS_SHAPES_VOCABULARY: ButtonTemplate[] = [
  // Colors
  {
    id: "red",
    text: "Red",
    message: "Red.",
    twoWord: "Red",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Red",
      hi: "लाल",
      es: "Rojo",
      fr: "Rouge",
      zh: "红色",
    },
  },
  {
    id: "blue",
    text: "Blue",
    message: "Blue.",
    twoWord: "Blue",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Blue",
      hi: "नीला",
      es: "Azul",
      fr: "Bleu",
      zh: "蓝色",
    },
  },
  {
    id: "green",
    text: "Green",
    message: "Green.",
    twoWord: "Green",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Green",
      hi: "हरा",
      es: "Verde",
      fr: "Vert",
      zh: "绿色",
    },
  },
  {
    id: "yellow",
    text: "Yellow",
    message: "Yellow.",
    twoWord: "Yellow",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Yellow",
      hi: "पीला",
      es: "Amarillo",
      fr: "Jaune",
      zh: "黄色",
    },
  },
  {
    id: "orange",
    text: "Orange",
    message: "Orange.",
    twoWord: "Orange",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Orange",
      hi: "नारंगी",
      es: "Naranja",
      fr: "Orange",
      zh: "橙色",
    },
  },
  {
    id: "purple",
    text: "Purple",
    message: "Purple.",
    twoWord: "Purple",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Purple",
      hi: "बैंगनी",
      es: "Morado",
      fr: "Violet",
      zh: "紫色",
    },
  },
  {
    id: "pink",
    text: "Pink",
    message: "Pink.",
    twoWord: "Pink",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Pink",
      hi: "गुलाबी",
      es: "Rosa",
      fr: "Rose",
      zh: "粉色",
    },
  },
  {
    id: "black",
    text: "Black",
    message: "Black.",
    twoWord: "Black",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Black",
      hi: "काला",
      es: "Negro",
      fr: "Noir",
      zh: "黑色",
    },
  },
  {
    id: "white",
    text: "White",
    message: "White.",
    twoWord: "White",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "White",
      hi: "सफेद",
      es: "Blanco",
      fr: "Blanc",
      zh: "白色",
    },
  },
  {
    id: "brown",
    text: "Brown",
    message: "Brown.",
    twoWord: "Brown",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Brown",
      hi: "भूरा",
      es: "Marrón",
      fr: "Marron",
      zh: "棕色",
    },
  },
  {
    id: "gray",
    text: "Gray",
    message: "Gray.",
    twoWord: "Gray",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Gray",
      hi: "ग्रे",
      es: "Gris",
      fr: "Gris",
      zh: "灰色",
    },
  },
  // Shapes
  {
    id: "circle",
    text: "Circle",
    message: "Circle.",
    twoWord: "Circle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Circle",
      hi: "वृत्त",
      es: "Círculo",
      fr: "Cercle",
      zh: "圆形",
    },
  },
  {
    id: "square",
    text: "Square",
    message: "Square.",
    twoWord: "Square",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Square",
      hi: "वर्ग",
      es: "Cuadrado",
      fr: "Carré",
      zh: "正方形",
    },
  },
  {
    id: "triangle",
    text: "Triangle",
    message: "Triangle.",
    twoWord: "Triangle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Triangle",
      hi: "त्रिभुज",
      es: "Triángulo",
      fr: "Triangle",
      zh: "三角形",
    },
  },
  {
    id: "rectangle",
    text: "Rectangle",
    message: "Rectangle.",
    twoWord: "Rectangle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Rectangle",
      hi: "आयत",
      es: "Rectángulo",
      fr: "Rectangle",
      zh: "长方形",
    },
  },
  {
    id: "star",
    text: "Star",
    message: "Star.",
    twoWord: "Star",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Star",
      hi: "तारा",
      es: "Estrella",
      fr: "Étoile",
      zh: "星星",
    },
  },
  {
    id: "heart",
    text: "Heart",
    message: "Heart.",
    twoWord: "Heart",
    category: "colors-shapes",
    color: "#F39C12",
    translations: {
      en: "Heart",
      hi: "दिल",
      es: "Corazón",
      fr: "Cœur",
      zh: "心形",
    },
  },
];
