import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const COLORS_SHAPES_VOCABULARY: ButtonTemplate[] = [
  // Colors
  {
    id: "red",
    text: "Red",
    message: "Red.",
    twoWord: "Red",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("red"),
  },
  {
    id: "blue",
    text: "Blue",
    message: "Blue.",
    twoWord: "Blue",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("blue"),
  },
  {
    id: "green",
    text: "Green",
    message: "Green.",
    twoWord: "Green",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("green"),
  },
  {
    id: "yellow",
    text: "Yellow",
    message: "Yellow.",
    twoWord: "Yellow",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("yellow"),
  },
  {
    id: "orange-color",
    text: "Orange",
    message: "Orange.",
    twoWord: "Orange",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("orange"),
  },
  {
    id: "purple",
    text: "Purple",
    message: "Purple.",
    twoWord: "Purple",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("purple"),
  },
  {
    id: "pink",
    text: "Pink",
    message: "Pink.",
    twoWord: "Pink",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("pink"),
  },
  {
    id: "black",
    text: "Black",
    message: "Black.",
    twoWord: "Black",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("black"),
  },
  {
    id: "white",
    text: "White",
    message: "White.",
    twoWord: "White",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("white"),
  },
  {
    id: "brown",
    text: "Brown",
    message: "Brown.",
    twoWord: "Brown",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("brown"),
  },
  {
    id: "gray",
    text: "Gray",
    message: "Gray.",
    twoWord: "Gray",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("gray"),
  },
  // Shapes
  {
    id: "circle",
    text: "Circle",
    message: "Circle.",
    twoWord: "Circle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("circle"),
  },
  {
    id: "square",
    text: "Square",
    message: "Square.",
    twoWord: "Square",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("square"),
  },
  {
    id: "triangle",
    text: "Triangle",
    message: "Triangle.",
    twoWord: "Triangle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("triangle"),
  },
  {
    id: "rectangle",
    text: "Rectangle",
    message: "Rectangle.",
    twoWord: "Rectangle",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("rectangle"),
  },
  {
    id: "star",
    text: "Star",
    message: "Star.",
    twoWord: "Star",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("star"),
  },
  {
    id: "heart",
    text: "Heart",
    message: "Heart.",
    twoWord: "Heart",
    category: "colors-shapes",
    color: "#F39C12",
    translations: getTranslationsForWord("heart"),
  },
];
