import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const DESCRIPTORS_VOCABULARY: ButtonTemplate[] = [
  {
    id: "big",
    text: "Big",
    message: "Big",
    twoWord: "Big",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("big"),
  },
  {
    id: "small",
    text: "Small",
    message: "Small",
    twoWord: "Small",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("small"),
  },
  {
    id: "hot",
    text: "Hot",
    message: "Hot",
    twoWord: "Hot",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("hot"),
  },
  {
    id: "cold",
    text: "Cold",
    message: "Cold",
    twoWord: "Cold",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("cold"),
  },
  {
    id: "fast",
    text: "Fast",
    message: "Fast",
    twoWord: "Fast",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("fast"),
  },
  {
    id: "slow",
    text: "Slow",
    message: "Slow",
    twoWord: "Slow",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("slow"),
  },
  {
    id: "good",
    text: "Good",
    message: "Good",
    twoWord: "Good",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("good"),
  },
  {
    id: "bad",
    text: "Bad",
    message: "Bad",
    twoWord: "Bad",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("bad"),
  },
  {
    id: "more",
    text: "More",
    message: "More",
    twoWord: "More",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("more"),
  },
  {
    id: "less",
    text: "Less",
    message: "Less",
    twoWord: "Less",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("less"),
  },
  {
    id: "all",
    text: "All",
    message: "All",
    twoWord: "All",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("all"),
  },
  {
    id: "some",
    text: "Some",
    message: "Some",
    twoWord: "Some",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("some"),
  },
  {
    id: "same",
    text: "Same",
    message: "Same",
    twoWord: "Same",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("same"),
  },
  {
    id: "different",
    text: "Different",
    message: "Different",
    twoWord: "Different",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("different"),
  },
  {
    id: "first",
    text: "First",
    message: "First",
    twoWord: "First",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("first"),
  },
  {
    id: "last",
    text: "Last",
    message: "Last",
    twoWord: "Last",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("last"),
  },
  {
    id: "next",
    text: "Next",
    message: "Next",
    twoWord: "Next",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("next"),
  },
  {
    id: "again",
    text: "Again",
    message: "Again",
    twoWord: "Again",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("again"),
  },
  {
    id: "clean",
    text: "Clean",
    message: "Clean",
    twoWord: "Clean",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("clean"),
  },
  {
    id: "dirty",
    text: "Dirty",
    message: "Dirty",
    twoWord: "Dirty",
    category: "descriptors",
    color: "#16A085",
    translations: getTranslationsForWord("dirty"),
  },
];
