import { ButtonTemplate } from "../../types";

export const EMOTIONS_VOCABULARY: ButtonTemplate[] = [
  // Positive Emotions
  {
    id: "happy",
    text: "Happy",
    message: "I am happy.",
    twoWord: "Am happy",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: {
      en: "Happy",
      hi: "खुश",
      es: "Feliz",
      fr: "Heureux",
      zh: "快乐",
    },
  },
  {
    id: "excited",
    text: "Excited",
    message: "I am excited.",
    twoWord: "Am excited",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: {
      en: "Excited",
      hi: "उत्साहित",
      es: "Emocionado",
      fr: "Excité",
      zh: "兴奋",
    },
  },
  {
    id: "proud",
    text: "Proud",
    message: "I am proud.",
    twoWord: "Am proud",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: {
      en: "Proud",
      hi: "गर्व",
      es: "Orgulloso",
      fr: "Fier",
      zh: "骄傲",
    },
  },
  {
    id: "calm",
    text: "Calm",
    message: "I am calm.",
    twoWord: "Am calm",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: {
      en: "Calm",
      hi: "शांत",
      es: "Tranquilo",
      fr: "Calme",
      zh: "平静",
    },
  },

  // Negative Emotions
  {
    id: "sad",
    text: "Sad",
    message: "I am sad.",
    twoWord: "Am sad",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Sad",
      hi: "दुखी",
      es: "Triste",
      fr: "Triste",
      zh: "悲伤",
    },
  },
  {
    id: "angry",
    text: "Angry",
    message: "I am angry.",
    twoWord: "Am angry",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Angry",
      hi: "गुस्सा",
      es: "Enojado",
      fr: "En colère",
      zh: "生气",
    },
  },
  {
    id: "scared",
    text: "Scared",
    message: "I am scared.",
    twoWord: "Am scared",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Scared",
      hi: "डरा हुआ",
      es: "Asustado",
      fr: "Effrayé",
      zh: "害怕",
    },
  },
  {
    id: "worried",
    text: "Worried",
    message: "I am worried.",
    twoWord: "Am worried",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Worried",
      hi: "चिंतित",
      es: "Preocupado",
      fr: "Inquiet",
      zh: "担心",
    },
  },
  {
    id: "tired",
    text: "Tired",
    message: "I am tired.",
    twoWord: "Am tired",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Tired",
      hi: "थका हुआ",
      es: "Cansado",
      fr: "Fatigué",
      zh: "疲倦",
    },
  },
  {
    id: "sick",
    text: "Sick",
    message: "I am sick.",
    twoWord: "Am sick",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Sick",
      hi: "बीमार",
      es: "Enfermo",
      fr: "Malade",
      zh: "生病",
    },
  },
  {
    id: "hurt",
    text: "Hurt",
    message: "I am hurt.",
    twoWord: "Am hurt",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Hurt",
      hi: "दर्द",
      es: "Herido",
      fr: "Blessé",
      zh: "受伤",
    },
  },
  {
    id: "lonely",
    text: "Lonely",
    message: "I am lonely.",
    twoWord: "Am lonely",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: {
      en: "Lonely",
      hi: "अकेला",
      es: "Solo",
      fr: "Seul",
      zh: "孤独",
    },
  },

  // Neutral Emotions
  {
    id: "surprised",
    text: "Surprised",
    message: "I am surprised.",
    twoWord: "Am surprised",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: {
      en: "Surprised",
      hi: "हैरान",
      es: "Sorprendido",
      fr: "Surpris",
      zh: "惊讶",
    },
  },
  {
    id: "bored",
    text: "Bored",
    message: "I am bored.",
    twoWord: "Am bored",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: {
      en: "Bored",
      hi: "बोर",
      es: "Aburrido",
      fr: "Ennuyé",
      zh: "无聊",
    },
  },
  {
    id: "silly",
    text: "Silly",
    message: "I am being silly.",
    twoWord: "Am silly",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: {
      en: "Silly",
      hi: "मूर्ख",
      es: "Tonto",
      fr: "Bête",
      zh: "傻",
    },
  },
];
