import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const EMOTIONS_VOCABULARY: ButtonTemplate[] = [
  // Positive Emotions
  {
    id: "happy",
    text: "Happy",
    message: "I am happy.",
    twoWord: "Am happy",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: getTranslationsForWord("happy"),
  },
  {
    id: "excited",
    text: "Excited",
    message: "I am excited.",
    twoWord: "Am excited",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: getTranslationsForWord("excited"),
  },
  {
    id: "proud",
    text: "Proud",
    message: "I am proud.",
    twoWord: "Am proud",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: getTranslationsForWord("proud"),
  },
  {
    id: "calm",
    text: "Calm",
    message: "I am calm.",
    twoWord: "Am calm",
    category: "emotions",
    subCategory: "positive",
    color: "#F1C40F",
    translations: getTranslationsForWord("calm"),
  },

  // Negative Emotions
  {
    id: "sad",
    text: "Sad",
    message: "I am sad.",
    twoWord: "Am sad",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("sad"),
  },
  {
    id: "angry",
    text: "Angry",
    message: "I am angry.",
    twoWord: "Am angry",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("angry"),
  },
  {
    id: "scared",
    text: "Scared",
    message: "I am scared.",
    twoWord: "Am scared",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("scared"),
  },
  {
    id: "worried",
    text: "Worried",
    message: "I am worried.",
    twoWord: "Am worried",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("worried"),
  },
  {
    id: "tired",
    text: "Tired",
    message: "I am tired.",
    twoWord: "Am tired",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("tired"),
  },
  {
    id: "sick",
    text: "Sick",
    message: "I am sick.",
    twoWord: "Am sick",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("sick"),
  },
  {
    id: "hurt",
    text: "Hurt",
    message: "I am hurt.",
    twoWord: "Am hurt",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("hurt"),
  },
  {
    id: "lonely",
    text: "Lonely",
    message: "I am lonely.",
    twoWord: "Am lonely",
    category: "emotions",
    subCategory: "negative",
    color: "#F1C40F",
    translations: getTranslationsForWord("lonely"),
  },

  // Neutral Emotions
  {
    id: "surprised",
    text: "Surprised",
    message: "I am surprised.",
    twoWord: "Am surprised",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: getTranslationsForWord("surprised"),
  },
  {
    id: "bored",
    text: "Bored",
    message: "I am bored.",
    twoWord: "Am bored",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: getTranslationsForWord("bored"),
  },
  {
    id: "silly",
    text: "Silly",
    message: "I am being silly.",
    twoWord: "Am silly",
    category: "emotions",
    subCategory: "neutral",
    color: "#F1C40F",
    translations: getTranslationsForWord("silly"),
  },
];
