import { ButtonTemplate } from "../../types";

export const FOOD_VOCABULARY: ButtonTemplate[] = [
  // Staples
  {
    id: "rice",
    text: "Rice",
    message: "I want rice.",
    twoWord: "Want rice",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: {
      en: "Rice",
      hi: "चावल",
      es: "Arroz",
      fr: "Riz",
      zh: "米饭",
    },
  },
  {
    id: "bread",
    text: "Bread",
    message: "I want bread.",
    twoWord: "Want bread",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: {
      en: "Bread",
      hi: "रोटी",
      es: "Pan",
      fr: "Pain",
      zh: "面包",
    },
  },
  {
    id: "pasta",
    text: "Pasta",
    message: "I want pasta.",
    twoWord: "Want pasta",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: {
      en: "Pasta",
      hi: "पास्ता",
      es: "Pasta",
      fr: "Pâtes",
      zh: "意大利面",
    },
  },
  {
    id: "cereal",
    text: "Cereal",
    message: "I want cereal.",
    twoWord: "Want cereal",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: {
      en: "Cereal",
      hi: "सीरियल",
      es: "Cereal",
      fr: "Céréales",
      zh: "麦片",
    },
  },
  {
    id: "soup",
    text: "Soup",
    message: "I want soup.",
    twoWord: "Want soup",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: {
      en: "Soup",
      hi: "सूप",
      es: "Sopa",
      fr: "Soupe",
      zh: "汤",
    },
  },

  // Proteins
  {
    id: "chicken",
    text: "Chicken",
    message: "I want chicken.",
    twoWord: "Want chicken",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Chicken",
      hi: "मुर्गा",
      es: "Pollo",
      fr: "Poulet",
      zh: "鸡肉",
    },
  },
  {
    id: "fish",
    text: "Fish",
    message: "I want fish.",
    twoWord: "Want fish",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Fish",
      hi: "मछली",
      es: "Pescado",
      fr: "Poisson",
      zh: "鱼",
    },
  },
  {
    id: "egg",
    text: "Egg",
    message: "I want an egg.",
    twoWord: "Want egg",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Egg",
      hi: "अंडा",
      es: "Huevo",
      fr: "Œuf",
      zh: "鸡蛋",
    },
  },
  {
    id: "meat",
    text: "Meat",
    message: "I want meat.",
    twoWord: "Want meat",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Meat",
      hi: "मांस",
      es: "Carne",
      fr: "Viande",
      zh: "肉",
    },
  },
  {
    id: "beans",
    text: "Beans",
    message: "I want beans.",
    twoWord: "Want beans",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Beans",
      hi: "बीन्स",
      es: "Frijoles",
      fr: "Haricots",
      zh: "豆子",
    },
  },
  {
    id: "cheese",
    text: "Cheese",
    message: "I want cheese.",
    twoWord: "Want cheese",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: {
      en: "Cheese",
      hi: "पनीर",
      es: "Queso",
      fr: "Fromage",
      zh: "奶酪",
    },
  },

  // Fruits
  {
    id: "apple",
    text: "Apple",
    message: "I want an apple.",
    twoWord: "Want apple",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Apple",
      hi: "सेब",
      es: "Manzana",
      fr: "Pomme",
      zh: "苹果",
    },
  },
  {
    id: "banana",
    text: "Banana",
    message: "I want a banana.",
    twoWord: "Want banana",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Banana",
      hi: "केला",
      es: "Plátano",
      fr: "Banane",
      zh: "香蕉",
    },
  },
  {
    id: "orange",
    text: "Orange",
    message: "I want an orange.",
    twoWord: "Want orange",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Orange",
      hi: "संतरा",
      es: "Naranja",
      fr: "Orange",
      zh: "橙子",
    },
  },
  {
    id: "grape",
    text: "Grape",
    message: "I want grapes.",
    twoWord: "Want grape",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Grape",
      hi: "अंगूर",
      es: "Uva",
      fr: "Raisin",
      zh: "葡萄",
    },
  },
  {
    id: "mango",
    text: "Mango",
    message: "I want a mango.",
    twoWord: "Want mango",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Mango",
      hi: "आम",
      es: "Mango",
      fr: "Mangue",
      zh: "芒果",
    },
  },
  {
    id: "strawberry",
    text: "Strawberry",
    message: "I want strawberries.",
    twoWord: "Want strawberry",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Strawberry",
      hi: "स्ट्रॉबेरी",
      es: "Fresa",
      fr: "Fraise",
      zh: "草莓",
    },
  },
  {
    id: "watermelon",
    text: "Watermelon",
    message: "I want watermelon.",
    twoWord: "Want watermelon",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: {
      en: "Watermelon",
      hi: "तरबूज",
      es: "Sandía",
      fr: "Pastèque",
      zh: "西瓜",
    },
  },

  // Vegetables
  {
    id: "carrot",
    text: "Carrot",
    message: "I want a carrot.",
    twoWord: "Want carrot",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Carrot",
      hi: "गाजर",
      es: "Zanahoria",
      fr: "Carotte",
      zh: "胡萝卜",
    },
  },
  {
    id: "potato",
    text: "Potato",
    message: "I want a potato.",
    twoWord: "Want potato",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Potato",
      hi: "आलू",
      es: "Papa",
      fr: "Pomme de terre",
      zh: "土豆",
    },
  },
  {
    id: "tomato",
    text: "Tomato",
    message: "I want a tomato.",
    twoWord: "Want tomato",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Tomato",
      hi: "टमाटर",
      es: "Tomate",
      fr: "Tomate",
      zh: "西红柿",
    },
  },
  {
    id: "cucumber",
    text: "Cucumber",
    message: "I want a cucumber.",
    twoWord: "Want cucumber",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Cucumber",
      hi: "खीरा",
      es: "Pepino",
      fr: "Concombre",
      zh: "黄瓜",
    },
  },
  {
    id: "corn",
    text: "Corn",
    message: "I want corn.",
    twoWord: "Want corn",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Corn",
      hi: "मक्का",
      es: "Maíz",
      fr: "Maïs",
      zh: "玉米",
    },
  },
  {
    id: "peas",
    text: "Peas",
    message: "I want peas.",
    twoWord: "Want peas",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Peas",
      hi: "मटर",
      es: "Guisantes",
      fr: "Pois",
      zh: "豌豆",
    },
  },
  {
    id: "broccoli",
    text: "Broccoli",
    message: "I want broccoli.",
    twoWord: "Want broccoli",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: {
      en: "Broccoli",
      hi: "ब्रोकोली",
      es: "Brócoli",
      fr: "Brocoli",
      zh: "西兰花",
    },
  },

  // Snacks
  {
    id: "cookie",
    text: "Cookie",
    message: "I want a cookie.",
    twoWord: "Want cookie",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Cookie",
      hi: "कुकी",
      es: "Galleta",
      fr: "Biscuit",
      zh: "饼干",
    },
  },
  {
    id: "candy",
    text: "Candy",
    message: "I want candy.",
    twoWord: "Want candy",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Candy",
      hi: "कैंडी",
      es: "Dulce",
      fr: "Bonbon",
      zh: "糖果",
    },
  },
  {
    id: "chips",
    text: "Chips",
    message: "I want chips.",
    twoWord: "Want chips",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Chips",
      hi: "चिप्स",
      es: "Papas fritas",
      fr: "Chips",
      zh: "薯片",
    },
  },
  {
    id: "cake",
    text: "Cake",
    message: "I want cake.",
    twoWord: "Want cake",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Cake",
      hi: "केक",
      es: "Pastel",
      fr: "Gâteau",
      zh: "蛋糕",
    },
  },
  {
    id: "ice-cream",
    text: "Ice Cream",
    message: "I want ice cream.",
    twoWord: "Want ice cream",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Ice Cream",
      hi: "आइसक्रीम",
      es: "Helado",
      fr: "Crème glacée",
      zh: "冰淇淋",
    },
  },
  {
    id: "popcorn",
    text: "Popcorn",
    message: "I want popcorn.",
    twoWord: "Want popcorn",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: {
      en: "Popcorn",
      hi: "पॉपकॉर्न",
      es: "Palomitas",
      fr: "Pop-corn",
      zh: "爆米花",
    },
  },

  // Drinks
  {
    id: "water",
    text: "Water",
    message: "I want water.",
    twoWord: "Want water",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Water",
      hi: "पानी",
      es: "Agua",
      fr: "Eau",
      zh: "水",
    },
  },
  {
    id: "milk",
    text: "Milk",
    message: "I want milk.",
    twoWord: "Want milk",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Milk",
      hi: "दूध",
      es: "Leche",
      fr: "Lait",
      zh: "牛奶",
    },
  },
  {
    id: "juice",
    text: "Juice",
    message: "I want juice.",
    twoWord: "Want juice",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Juice",
      hi: "जूस",
      es: "Jugo",
      fr: "Jus",
      zh: "果汁",
    },
  },
  {
    id: "tea",
    text: "Tea",
    message: "I want tea.",
    twoWord: "Want tea",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Tea",
      hi: "चाय",
      es: "Té",
      fr: "Thé",
      zh: "茶",
    },
  },
  {
    id: "coffee",
    text: "Coffee",
    message: "I want coffee.",
    twoWord: "Want coffee",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Coffee",
      hi: "कॉफी",
      es: "Café",
      fr: "Café",
      zh: "咖啡",
    },
  },
  {
    id: "soda",
    text: "Soda",
    message: "I want soda.",
    twoWord: "Want soda",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: {
      en: "Soda",
      hi: "सोडा",
      es: "Refresco",
      fr: "Soda",
      zh: "汽水",
    },
  },
];
