import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const FOOD_VOCABULARY: ButtonTemplate[] = [
  // Staples
  {
    id: "rice",
    text: "Rice",
    message: "I want rice.",
    twoWord: "Want rice",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: getTranslationsForWord("rice"),
  },
  {
    id: "bread",
    text: "Bread",
    message: "I want bread.",
    twoWord: "Want bread",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: getTranslationsForWord("bread"),
  },
  {
    id: "pasta",
    text: "Pasta",
    message: "I want pasta.",
    twoWord: "Want pasta",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: getTranslationsForWord("pasta"),
  },
  {
    id: "cereal",
    text: "Cereal",
    message: "I want cereal.",
    twoWord: "Want cereal",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: getTranslationsForWord("cereal"),
  },
  {
    id: "soup",
    text: "Soup",
    message: "I want soup.",
    twoWord: "Want soup",
    category: "food",
    subCategory: "staples",
    color: "#E74C3C",
    translations: getTranslationsForWord("soup"),
  },

  // Proteins
  {
    id: "chicken-food",
    text: "Chicken",
    message: "I want chicken.",
    twoWord: "Want chicken",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("chicken-food"),
  },
  {
    id: "fish-food",
    text: "Fish",
    message: "I want fish.",
    twoWord: "Want fish",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("fish-food"),
  },
  {
    id: "egg",
    text: "Egg",
    message: "I want an egg.",
    twoWord: "Want egg",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("egg"),
  },
  {
    id: "meat",
    text: "Meat",
    message: "I want meat.",
    twoWord: "Want meat",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("meat"),
  },
  {
    id: "beans",
    text: "Beans",
    message: "I want beans.",
    twoWord: "Want beans",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("beans"),
  },
  {
    id: "cheese",
    text: "Cheese",
    message: "I want cheese.",
    twoWord: "Want cheese",
    category: "food",
    subCategory: "proteins",
    color: "#E74C3C",
    translations: getTranslationsForWord("cheese"),
  },

  // Fruits
  {
    id: "apple",
    text: "Apple",
    message: "I want an apple.",
    twoWord: "Want apple",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("apple"),
  },
  {
    id: "banana",
    text: "Banana",
    message: "I want a banana.",
    twoWord: "Want banana",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("banana"),
  },
  {
    id: "orange-fruit",
    text: "Orange",
    message: "I want an orange.",
    twoWord: "Want orange",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("orange-fruit"),
  },
  {
    id: "grape",
    text: "Grape",
    message: "I want grapes.",
    twoWord: "Want grape",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("grape"),
  },
  {
    id: "mango",
    text: "Mango",
    message: "I want a mango.",
    twoWord: "Want mango",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("mango"),
  },
  {
    id: "strawberry",
    text: "Strawberry",
    message: "I want strawberries.",
    twoWord: "Want strawberry",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("strawberry"),
  },
  {
    id: "watermelon",
    text: "Watermelon",
    message: "I want watermelon.",
    twoWord: "Want watermelon",
    category: "food",
    subCategory: "fruits",
    color: "#E74C3C",
    translations: getTranslationsForWord("watermelon"),
  },

  // Vegetables
  {
    id: "carrot",
    text: "Carrot",
    message: "I want a carrot.",
    twoWord: "Want carrot",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("carrot"),
  },
  {
    id: "potato",
    text: "Potato",
    message: "I want a potato.",
    twoWord: "Want potato",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("potato"),
  },
  {
    id: "tomato",
    text: "Tomato",
    message: "I want a tomato.",
    twoWord: "Want tomato",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("tomato"),
  },
  {
    id: "cucumber",
    text: "Cucumber",
    message: "I want a cucumber.",
    twoWord: "Want cucumber",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("cucumber"),
  },
  {
    id: "corn",
    text: "Corn",
    message: "I want corn.",
    twoWord: "Want corn",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("corn"),
  },
  {
    id: "peas",
    text: "Peas",
    message: "I want peas.",
    twoWord: "Want peas",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("peas"),
  },
  {
    id: "broccoli",
    text: "Broccoli",
    message: "I want broccoli.",
    twoWord: "Want broccoli",
    category: "food",
    subCategory: "vegetables",
    color: "#E74C3C",
    translations: getTranslationsForWord("broccoli"),
  },

  // Snacks
  {
    id: "cookie",
    text: "Cookie",
    message: "I want a cookie.",
    twoWord: "Want cookie",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("cookie"),
  },
  {
    id: "candy",
    text: "Candy",
    message: "I want candy.",
    twoWord: "Want candy",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("candy"),
  },
  {
    id: "chips",
    text: "Chips",
    message: "I want chips.",
    twoWord: "Want chips",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("chips"),
  },
  {
    id: "cake",
    text: "Cake",
    message: "I want cake.",
    twoWord: "Want cake",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("cake"),
  },
  {
    id: "ice-cream",
    text: "Ice Cream",
    message: "I want ice cream.",
    twoWord: "Want ice cream",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("ice-cream"),
  },
  {
    id: "popcorn",
    text: "Popcorn",
    message: "I want popcorn.",
    twoWord: "Want popcorn",
    category: "food",
    subCategory: "snacks",
    color: "#E74C3C",
    translations: getTranslationsForWord("popcorn"),
  },

  // Drinks
  {
    id: "water",
    text: "Water",
    message: "I want water.",
    twoWord: "Want water",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("water"),
  },
  {
    id: "milk",
    text: "Milk",
    message: "I want milk.",
    twoWord: "Want milk",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("milk"),
  },
  {
    id: "juice",
    text: "Juice",
    message: "I want juice.",
    twoWord: "Want juice",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("juice"),
  },
  {
    id: "tea",
    text: "Tea",
    message: "I want tea.",
    twoWord: "Want tea",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("tea"),
  },
  {
    id: "coffee",
    text: "Coffee",
    message: "I want coffee.",
    twoWord: "Want coffee",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("coffee"),
  },
  {
    id: "soda",
    text: "Soda",
    message: "I want soda.",
    twoWord: "Want soda",
    category: "food",
    subCategory: "drinks",
    color: "#E74C3C",
    translations: getTranslationsForWord("soda"),
  },
];
