import { ButtonTemplate } from "../../types";

export const HOME_VOCABULARY: ButtonTemplate[] = [
  // Furniture
  {
    id: "house",
    text: "House",
    message: "I want to go home.",
    twoWord: "Want house",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: {
      en: "House",
      hi: "घर",
      es: "Casa",
      fr: "Maison",
      zh: "房子",
    },
  },
  {
    id: "bed",
    text: "Bed",
    message: "I want to sleep.",
    twoWord: "Want bed",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: {
      en: "Bed",
      hi: "बिस्तर",
      es: "Cama",
      fr: "Lit",
      zh: "床",
    },
  },
  {
    id: "chair",
    text: "Chair",
    message: "I want to sit.",
    twoWord: "Want chair",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: {
      en: "Chair",
      hi: "कुर्सी",
      es: "Silla",
      fr: "Chaise",
      zh: "椅子",
    },
  },
  {
    id: "table",
    text: "Table",
    message: "I want to use the table.",
    twoWord: "Want table",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: {
      en: "Table",
      hi: "मेज़",
      es: "Mesa",
      fr: "Table",
      zh: "桌子",
    },
  },

  // Electronics
  {
    id: "tv",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: {
      en: "TV",
      hi: "टीवी",
      es: "TV",
      fr: "TV",
      zh: "电视",
    },
  },
  {
    id: "phone",
    text: "Phone",
    message: "I want to use the phone.",
    twoWord: "Want phone",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: {
      en: "Phone",
      hi: "फ़ोन",
      es: "Teléfono",
      fr: "Téléphone",
      zh: "电话",
    },
  },
  {
    id: "computer",
    text: "Computer",
    message: "I want to use the computer.",
    twoWord: "Want computer",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: {
      en: "Computer",
      hi: "कंप्यूटर",
      es: "Computadora",
      fr: "Ordinateur",
      zh: "电脑",
    },
  },

  // Rooms
  {
    id: "light",
    text: "Light",
    message: "Turn on the light.",
    twoWord: "Want light",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: {
      en: "Light",
      hi: "लाइट",
      es: "Luz",
      fr: "Lumière",
      zh: "灯",
    },
  },
  {
    id: "door",
    text: "Door",
    message: "Open the door.",
    twoWord: "Want door",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: {
      en: "Door",
      hi: "दरवाज़ा",
      es: "Puerta",
      fr: "Porte",
      zh: "门",
    },
  },
  {
    id: "window",
    text: "Window",
    message: "Open the window.",
    twoWord: "Want window",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: {
      en: "Window",
      hi: "खिड़की",
      es: "Ventana",
      fr: "Fenêtre",
      zh: "窗户",
    },
  },
];
