import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const HOME_VOCABULARY: ButtonTemplate[] = [
  // Furniture
  {
    id: "house",
    text: "House",
    message: "I want to go home.",
    twoWord: "Want house",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: getTranslationsForWord("house"),
  },
  {
    id: "bed",
    text: "Bed",
    message: "I want to sleep.",
    twoWord: "Want bed",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: getTranslationsForWord("bed"),
  },
  {
    id: "chair",
    text: "Chair",
    message: "I want to sit.",
    twoWord: "Want chair",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: getTranslationsForWord("chair"),
  },
  {
    id: "table",
    text: "Table",
    message: "I want to use the table.",
    twoWord: "Want table",
    category: "home",
    subCategory: "furniture",
    color: "#4ECDC4",
    translations: getTranslationsForWord("table"),
  },

  // Electronics
  {
    id: "tv",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: getTranslationsForWord("tv"),
  },
  {
    id: "phone-home",
    text: "Phone",
    message: "I want to use the phone.",
    twoWord: "Want phone",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: getTranslationsForWord("phone-home"),
  },
  {
    id: "computer-home",
    text: "Computer",
    message: "I want to use the computer.",
    twoWord: "Want computer",
    category: "home",
    subCategory: "electronics",
    color: "#4ECDC4",
    translations: getTranslationsForWord("computer-home"),
  },

  // Rooms
  {
    id: "light",
    text: "Light",
    message: "Turn on the light.",
    twoWord: "Want light",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: getTranslationsForWord("light"),
  },
  {
    id: "door",
    text: "Door",
    message: "Open the door.",
    twoWord: "Want door",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: getTranslationsForWord("door"),
  },
  {
    id: "window",
    text: "Window",
    message: "Open the window.",
    twoWord: "Want window",
    category: "home",
    subCategory: "rooms",
    color: "#4ECDC4",
    translations: getTranslationsForWord("window"),
  },
];
