import { ButtonTemplate } from "../../types";

export const KITCHEN_VOCABULARY: ButtonTemplate[] = [
  // Utensils
  {
    id: "plate",
    text: "Plate",
    message: "I want a plate.",
    twoWord: "Want plate",
    category: "kitchen",
    subCategory: "utensils",
    color: "#FFB347",
    translations: {
      en: "Plate",
      hi: "प्लेट",
      es: "Plato",
      fr: "Assiette",
      zh: "盘子",
    },
  },
  {
    id: "cup",
    text: "Cup",
    message: "I want a cup.",
    twoWord: "Want cup",
    category: "kitchen",
    subCategory: "utensils",
    color: "#FFB347",
    translations: {
      en: "Cup",
      hi: "कप",
      es: "Taza",
      fr: "Tasse",
      zh: "杯子",
    },
  },
  {
    id: "spoon",
    text: "Spoon",
    message: "I want a spoon.",
    twoWord: "Want spoon",
    category: "kitchen",
    subCategory: "utensils",
    color: "#FFB347",
    translations: {
      en: "Spoon",
      hi: "चम्मच",
      es: "Cuchara",
      fr: "Cuillère",
      zh: "勺子",
    },
  },
  {
    id: "fork",
    text: "Fork",
    message: "I want a fork.",
    twoWord: "Want fork",
    category: "kitchen",
    subCategory: "utensils",
    color: "#FFB347",
    translations: {
      en: "Fork",
      hi: "कांटा",
      es: "Tenedor",
      fr: "Fourchette",
      zh: "叉子",
    },
  },
  {
    id: "knife",
    text: "Knife",
    message: "I want a knife.",
    twoWord: "Want knife",
    category: "kitchen",
    subCategory: "utensils",
    color: "#FFB347",
    translations: {
      en: "Knife",
      hi: "चाकू",
      es: "Cuchillo",
      fr: "Couteau",
      zh: "刀子",
    },
  },

  // Containers
  {
    id: "bowl",
    text: "Bowl",
    message: "I want a bowl.",
    twoWord: "Want bowl",
    category: "kitchen",
    subCategory: "containers",
    color: "#FFB347",
    translations: {
      en: "Bowl",
      hi: "कटोरा",
      es: "Tazón",
      fr: "Bol",
      zh: "碗",
    },
  },
  {
    id: "bottle",
    text: "Bottle",
    message: "I want a bottle.",
    twoWord: "Want bottle",
    category: "kitchen",
    subCategory: "containers",
    color: "#FFB347",
    translations: {
      en: "Bottle",
      hi: "बोतल",
      es: "Botella",
      fr: "Bouteille",
      zh: "瓶子",
    },
  },
];
