import { ButtonTemplate } from "../../types";

export const NUMBERS_TIME_VOCABULARY: ButtonTemplate[] = [
  // Numbers 1-20
  {
    id: "one",
    text: "1",
    message: "One.",
    twoWord: "One",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "One",
      hi: "एक",
      es: "Uno",
      fr: "Un",
      zh: "一",
    },
  },
  {
    id: "two",
    text: "2",
    message: "Two.",
    twoWord: "Two",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Two",
      hi: "दो",
      es: "Dos",
      fr: "Deux",
      zh: "二",
    },
  },
  {
    id: "three",
    text: "3",
    message: "Three.",
    twoWord: "Three",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Three",
      hi: "तीन",
      es: "Tres",
      fr: "Trois",
      zh: "三",
    },
  },
  {
    id: "four",
    text: "4",
    message: "Four.",
    twoWord: "Four",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Four",
      hi: "चार",
      es: "Cuatro",
      fr: "Quatre",
      zh: "四",
    },
  },
  {
    id: "five",
    text: "5",
    message: "Five.",
    twoWord: "Five",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Five",
      hi: "पांच",
      es: "Cinco",
      fr: "Cinq",
      zh: "五",
    },
  },
  {
    id: "six",
    text: "6",
    message: "Six.",
    twoWord: "Six",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Six",
      hi: "छह",
      es: "Seis",
      fr: "Six",
      zh: "六",
    },
  },
  {
    id: "seven",
    text: "7",
    message: "Seven.",
    twoWord: "Seven",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Seven",
      hi: "सात",
      es: "Siete",
      fr: "Sept",
      zh: "七",
    },
  },
  {
    id: "eight",
    text: "8",
    message: "Eight.",
    twoWord: "Eight",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Eight",
      hi: "आठ",
      es: "Ocho",
      fr: "Huit",
      zh: "八",
    },
  },
  {
    id: "nine",
    text: "9",
    message: "Nine.",
    twoWord: "Nine",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Nine",
      hi: "नौ",
      es: "Nueve",
      fr: "Neuf",
      zh: "九",
    },
  },
  {
    id: "ten",
    text: "10",
    message: "Ten.",
    twoWord: "Ten",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Ten",
      hi: "दस",
      es: "Diez",
      fr: "Dix",
      zh: "十",
    },
  },
  {
    id: "eleven",
    text: "11",
    message: "Eleven.",
    twoWord: "Eleven",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Eleven",
      hi: "ग्यारह",
      es: "Once",
      fr: "Onze",
      zh: "十一",
    },
  },
  {
    id: "twelve",
    text: "12",
    message: "Twelve.",
    twoWord: "Twelve",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Twelve",
      hi: "बारह",
      es: "Doce",
      fr: "Douze",
      zh: "十二",
    },
  },
  {
    id: "thirteen",
    text: "13",
    message: "Thirteen.",
    twoWord: "Thirteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Thirteen",
      hi: "तेरह",
      es: "Trece",
      fr: "Treize",
      zh: "十三",
    },
  },
  {
    id: "fourteen",
    text: "14",
    message: "Fourteen.",
    twoWord: "Fourteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Fourteen",
      hi: "चौदह",
      es: "Catorce",
      fr: "Quatorze",
      zh: "十四",
    },
  },
  {
    id: "fifteen",
    text: "15",
    message: "Fifteen.",
    twoWord: "Fifteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Fifteen",
      hi: "पंद्रह",
      es: "Quince",
      fr: "Quinze",
      zh: "十五",
    },
  },
  {
    id: "sixteen",
    text: "16",
    message: "Sixteen.",
    twoWord: "Sixteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Sixteen",
      hi: "सोलह",
      es: "Dieciséis",
      fr: "Seize",
      zh: "十六",
    },
  },
  {
    id: "seventeen",
    text: "17",
    message: "Seventeen.",
    twoWord: "Seventeen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Seventeen",
      hi: "सत्रह",
      es: "Diecisiete",
      fr: "Dix-sept",
      zh: "十七",
    },
  },
  {
    id: "eighteen",
    text: "18",
    message: "Eighteen.",
    twoWord: "Eighteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Eighteen",
      hi: "अठारह",
      es: "Dieciocho",
      fr: "Dix-huit",
      zh: "十八",
    },
  },
  {
    id: "nineteen",
    text: "19",
    message: "Nineteen.",
    twoWord: "Nineteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Nineteen",
      hi: "उन्नीस",
      es: "Diecinueve",
      fr: "Dix-neuf",
      zh: "十九",
    },
  },
  {
    id: "twenty",
    text: "20",
    message: "Twenty.",
    twoWord: "Twenty",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Twenty",
      hi: "बीस",
      es: "Veinte",
      fr: "Vingt",
      zh: "二十",
    },
  },
  {
    id: "thirty",
    text: "30",
    message: "Thirty.",
    twoWord: "Thirty",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Thirty",
      hi: "तीस",
      es: "Treinta",
      fr: "Trente",
      zh: "三十",
    },
  },
  {
    id: "forty",
    text: "40",
    message: "Forty.",
    twoWord: "Forty",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Forty",
      hi: "चालीस",
      es: "Cuarenta",
      fr: "Quarante",
      zh: "四十",
    },
  },
  {
    id: "fifty",
    text: "50",
    message: "Fifty.",
    twoWord: "Fifty",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Fifty",
      hi: "पचास",
      es: "Cincuenta",
      fr: "Cinquante",
      zh: "五十",
    },
  },
  {
    id: "hundred",
    text: "100",
    message: "Hundred.",
    twoWord: "Hundred",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Hundred",
      hi: "सौ",
      es: "Cien",
      fr: "Cent",
      zh: "一百",
    },
  },
  // Time
  {
    id: "morning",
    text: "Morning",
    message: "Good morning.",
    twoWord: "Good morning",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Morning",
      hi: "सुबह",
      es: "Mañana",
      fr: "Matin",
      zh: "早上",
    },
  },
  {
    id: "afternoon",
    text: "Afternoon",
    message: "Good afternoon.",
    twoWord: "Good afternoon",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Afternoon",
      hi: "दोपहर",
      es: "Tarde",
      fr: "Après-midi",
      zh: "下午",
    },
  },
  {
    id: "evening",
    text: "Evening",
    message: "Good evening.",
    twoWord: "Good evening",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Evening",
      hi: "शाम",
      es: "Noche",
      fr: "Soir",
      zh: "晚上",
    },
  },
  {
    id: "night",
    text: "Night",
    message: "Good night.",
    twoWord: "Good night",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Night",
      hi: "रात",
      es: "Noche",
      fr: "Nuit",
      zh: "夜晚",
    },
  },
  {
    id: "today",
    text: "Today",
    message: "Today.",
    twoWord: "Today",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Today",
      hi: "आज",
      es: "Hoy",
      fr: "Aujourd'hui",
      zh: "今天",
    },
  },
  {
    id: "tomorrow",
    text: "Tomorrow",
    message: "Tomorrow.",
    twoWord: "Tomorrow",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Tomorrow",
      hi: "कल",
      es: "Mañana",
      fr: "Demain",
      zh: "明天",
    },
  },
  {
    id: "yesterday",
    text: "Yesterday",
    message: "Yesterday.",
    twoWord: "Yesterday",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Yesterday",
      hi: "कल",
      es: "Ayer",
      fr: "Hier",
      zh: "昨天",
    },
  },
  {
    id: "now",
    text: "Now",
    message: "Now.",
    twoWord: "Now",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Now",
      hi: "अब",
      es: "Ahora",
      fr: "Maintenant",
      zh: "现在",
    },
  },
  {
    id: "later",
    text: "Later",
    message: "Later.",
    twoWord: "Later",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Later",
      hi: "बाद में",
      es: "Más tarde",
      fr: "Plus tard",
      zh: "稍后",
    },
  },
  {
    id: "soon",
    text: "Soon",
    message: "Soon.",
    twoWord: "Soon",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Soon",
      hi: "जल्द",
      es: "Pronto",
      fr: "Bientôt",
      zh: "很快",
    },
  },
  // Weather
  {
    id: "sun",
    text: "Sun",
    message: "The sun is shining.",
    twoWord: "Sun shining",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Sun",
      hi: "सूरज",
      es: "Sol",
      fr: "Soleil",
      zh: "太阳",
    },
  },
  {
    id: "rain",
    text: "Rain",
    message: "It is raining.",
    twoWord: "Is raining",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Rain",
      hi: "बारिश",
      es: "Lluvia",
      fr: "Pluie",
      zh: "雨",
    },
  },
  {
    id: "cloud",
    text: "Cloud",
    message: "It is cloudy.",
    twoWord: "Is cloudy",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Cloud",
      hi: "बादल",
      es: "Nube",
      fr: "Nuage",
      zh: "云",
    },
  },
  {
    id: "snow",
    text: "Snow",
    message: "It is snowing.",
    twoWord: "Is snowing",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Snow",
      hi: "बर्फ",
      es: "Nieve",
      fr: "Neige",
      zh: "雪",
    },
  },
  {
    id: "hot",
    text: "Hot",
    message: "It is hot.",
    twoWord: "Is hot",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Hot",
      hi: "गर्म",
      es: "Caliente",
      fr: "Chaud",
      zh: "热",
    },
  },
  {
    id: "cold",
    text: "Cold",
    message: "It is cold.",
    twoWord: "Is cold",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Cold",
      hi: "ठंडा",
      es: "Frío",
      fr: "Froid",
      zh: "冷",
    },
  },
  {
    id: "windy",
    text: "Windy",
    message: "It is windy.",
    twoWord: "Is windy",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Windy",
      hi: "हवा",
      es: "Ventoso",
      fr: "Venteux",
      zh: "有风",
    },
  },
  {
    id: "storm",
    text: "Storm",
    message: "There is a storm.",
    twoWord: "Is storm",
    category: "numbers-time",
    color: "#2980B9",
    translations: {
      en: "Storm",
      hi: "तूफान",
      es: "Tormenta",
      fr: "Tempête",
      zh: "暴风雨",
    },
  },
];
