import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const NUMBERS_TIME_VOCABULARY: ButtonTemplate[] = [
  // Numbers 1-20
  {
    id: "one",
    text: "1",
    message: "One.",
    twoWord: "One",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("one"),
  },
  {
    id: "two",
    text: "2",
    message: "Two.",
    twoWord: "Two",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("two"),
  },
  {
    id: "three",
    text: "3",
    message: "Three.",
    twoWord: "Three",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("three"),
  },
  {
    id: "four",
    text: "4",
    message: "Four.",
    twoWord: "Four",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("four"),
  },
  {
    id: "five",
    text: "5",
    message: "Five.",
    twoWord: "Five",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("five"),
  },
  {
    id: "six",
    text: "6",
    message: "Six.",
    twoWord: "Six",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("six"),
  },
  {
    id: "seven",
    text: "7",
    message: "Seven.",
    twoWord: "Seven",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("seven"),
  },
  {
    id: "eight",
    text: "8",
    message: "Eight.",
    twoWord: "Eight",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("eight"),
  },
  {
    id: "nine",
    text: "9",
    message: "Nine.",
    twoWord: "Nine",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("nine"),
  },
  {
    id: "ten",
    text: "10",
    message: "Ten.",
    twoWord: "Ten",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("ten"),
  },
  {
    id: "eleven",
    text: "11",
    message: "Eleven.",
    twoWord: "Eleven",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("eleven"),
  },
  {
    id: "twelve",
    text: "12",
    message: "Twelve.",
    twoWord: "Twelve",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("twelve"),
  },
  {
    id: "thirteen",
    text: "13",
    message: "Thirteen.",
    twoWord: "Thirteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("thirteen"),
  },
  {
    id: "fourteen",
    text: "14",
    message: "Fourteen.",
    twoWord: "Fourteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("fourteen"),
  },
  {
    id: "fifteen",
    text: "15",
    message: "Fifteen.",
    twoWord: "Fifteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("fifteen"),
  },
  {
    id: "sixteen",
    text: "16",
    message: "Sixteen.",
    twoWord: "Sixteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("sixteen"),
  },
  {
    id: "seventeen",
    text: "17",
    message: "Seventeen.",
    twoWord: "Seventeen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("seventeen"),
  },
  {
    id: "eighteen",
    text: "18",
    message: "Eighteen.",
    twoWord: "Eighteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("eighteen"),
  },
  {
    id: "nineteen",
    text: "19",
    message: "Nineteen.",
    twoWord: "Nineteen",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("nineteen"),
  },
  {
    id: "twenty",
    text: "20",
    message: "Twenty.",
    twoWord: "Twenty",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("twenty"),
  },
  {
    id: "thirty",
    text: "30",
    message: "Thirty.",
    twoWord: "Thirty",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("thirty"),
  },
  {
    id: "forty",
    text: "40",
    message: "Forty.",
    twoWord: "Forty",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("forty"),
  },
  {
    id: "fifty",
    text: "50",
    message: "Fifty.",
    twoWord: "Fifty",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("fifty"),
  },
  {
    id: "hundred",
    text: "100",
    message: "Hundred.",
    twoWord: "Hundred",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("hundred"),
  },
  // Time
  {
    id: "morning",
    text: "Morning",
    message: "Good morning.",
    twoWord: "Good morning",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("morning"),
  },
  {
    id: "afternoon",
    text: "Afternoon",
    message: "Good afternoon.",
    twoWord: "Good afternoon",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("afternoon"),
  },
  {
    id: "evening",
    text: "Evening",
    message: "Good evening.",
    twoWord: "Good evening",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("evening"),
  },
  {
    id: "night",
    text: "Night",
    message: "Good night.",
    twoWord: "Good night",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("night"),
  },
  {
    id: "today",
    text: "Today",
    message: "Today.",
    twoWord: "Today",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("today"),
  },
  {
    id: "tomorrow",
    text: "Tomorrow",
    message: "Tomorrow.",
    twoWord: "Tomorrow",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("tomorrow"),
  },
  {
    id: "yesterday",
    text: "Yesterday",
    message: "Yesterday.",
    twoWord: "Yesterday",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("yesterday"),
  },
  {
    id: "now",
    text: "Now",
    message: "Now.",
    twoWord: "Now",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("now"),
  },
  {
    id: "later",
    text: "Later",
    message: "Later.",
    twoWord: "Later",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("later"),
  },
  {
    id: "soon",
    text: "Soon",
    message: "Soon.",
    twoWord: "Soon",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("soon"),
  },
  // Weather
  {
    id: "sun",
    text: "Sun",
    message: "The sun is shining.",
    twoWord: "Sun shining",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("sun"),
  },
  {
    id: "rain",
    text: "Rain",
    message: "It is raining.",
    twoWord: "Is raining",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("rain"),
  },
  {
    id: "cloud",
    text: "Cloud",
    message: "It is cloudy.",
    twoWord: "Is cloudy",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("cloud"),
  },
  {
    id: "snow",
    text: "Snow",
    message: "It is snowing.",
    twoWord: "Is snowing",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("snow"),
  },
  {
    id: "hot",
    text: "Hot",
    message: "It is hot.",
    twoWord: "Is hot",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("hot"),
  },
  {
    id: "cold",
    text: "Cold",
    message: "It is cold.",
    twoWord: "Is cold",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("cold"),
  },
  {
    id: "windy",
    text: "Windy",
    message: "It is windy.",
    twoWord: "Is windy",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("windy"),
  },
  {
    id: "storm",
    text: "Storm",
    message: "There is a storm.",
    twoWord: "Is storm",
    category: "numbers-time",
    color: "#2980B9",
    translations: getTranslationsForWord("storm"),
  },
];
