import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const PEOPLE_VOCABULARY: ButtonTemplate[] = [
  {
    id: "mom",
    text: "Mom",
    message: "Mom!",
    twoWord: "Want mom",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("mom"),
  },
  {
    id: "dad",
    text: "Dad",
    message: "Dad!",
    twoWord: "Want dad",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("dad"),
  },
  {
    id: "friend",
    text: "Friend",
    message: "My friend.",
    twoWord: "My friend",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("friend"),
  },
  {
    id: "brother",
    text: "Brother",
    message: "My brother.",
    twoWord: "My brother",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("brother"),
  },
  {
    id: "sister",
    text: "Sister",
    message: "My sister.",
    twoWord: "My sister",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("sister"),
  },
  {
    id: "grandpa",
    text: "Grandpa",
    message: "My grandpa.",
    twoWord: "My grandpa",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("grandpa"),
  },
  {
    id: "grandma",
    text: "Grandma",
    message: "My grandma.",
    twoWord: "My grandma",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("grandma"),
  },
  {
    id: "uncle",
    text: "Uncle",
    message: "My uncle.",
    twoWord: "My uncle",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("uncle"),
  },
  {
    id: "aunt",
    text: "Aunt",
    message: "My aunt.",
    twoWord: "My aunt",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("aunt"),
  },
];
