import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const PLACES_VOCABULARY: ButtonTemplate[] = [
  {
    id: "park",
    text: "Park",
    message: "I want to go to the park.",
    twoWord: "Want park",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("park"),
  },
  {
    id: "store",
    text: "Store",
    message: "I want to go to the store.",
    twoWord: "Want store",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("store"),
  },
  {
    id: "playground",
    text: "Playground",
    message: "I want to go to the playground.",
    twoWord: "Want playground",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("playground"),
  },
  {
    id: "restaurant",
    text: "Restaurant",
    message: "I want to go to the restaurant.",
    twoWord: "Want restaurant",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("restaurant"),
  },
  {
    id: "mcdonalds",
    text: "McDonald's",
    message: "I want to go to McDonald's.",
    twoWord: "Want McDonald's",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("mcdonalds"),
  },
  {
    id: "hospital",
    text: "Hospital",
    message: "I want to go to the hospital.",
    twoWord: "Want hospital",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("hospital"),
  },
  {
    id: "library",
    text: "Library",
    message: "I want to go to the library.",
    twoWord: "Want library",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("library"),
  },
  {
    id: "beach",
    text: "Beach",
    message: "I want to go to the beach.",
    twoWord: "Want beach",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("beach"),
  },
];
