import { ButtonTemplate } from "../../types";

export const PLAY_VOCABULARY: ButtonTemplate[] = [
  // Basic Play
  {
    id: "play",
    text: "Play",
    message: "I want to play.",
    twoWord: "Want play",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Play",
      hi: "खेलना",
      es: "Jugar",
      fr: "Jouer",
      zh: "玩",
    },
  },
  {
    id: "toy",
    text: "Toy",
    message: "I want a toy.",
    twoWord: "Want toy",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Toy",
      hi: "खिलौना",
      es: "Juguete",
      fr: "Jouet",
      zh: "玩具",
    },
  },
  {
    id: "game",
    text: "Game",
    message: "I want to play a game.",
    twoWord: "Want game",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Game",
      hi: "खेल",
      es: "Juego",
      fr: "Jeu",
      zh: "游戏",
    },
  },
  {
    id: "ball",
    text: "Ball",
    message: "I want the ball.",
    twoWord: "Want ball",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Ball",
      hi: "गेंद",
      es: "Pelota",
      fr: "Balle",
      zh: "球",
    },
  },
  {
    id: "doll",
    text: "Doll",
    message: "I want the doll.",
    twoWord: "Want doll",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Doll",
      hi: "गुड़िया",
      es: "Muñeca",
      fr: "Poupée",
      zh: "娃娃",
    },
  },
  {
    id: "blocks",
    text: "Blocks",
    message: "I want the blocks.",
    twoWord: "Want blocks",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Blocks",
      hi: "ब्लॉक्स",
      es: "Bloques",
      fr: "Blocs",
      zh: "积木",
    },
  },
  {
    id: "book",
    text: "Book",
    message: "I want to read a book.",
    twoWord: "Want book",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Book",
      hi: "किताब",
      es: "Libro",
      fr: "Livre",
      zh: "书",
    },
  },
  {
    id: "music",
    text: "Music",
    message: "I want music.",
    twoWord: "Want music",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Music",
      hi: "संगीत",
      es: "Música",
      fr: "Musique",
      zh: "音乐",
    },
  },
  {
    id: "dance",
    text: "Dance",
    message: "I want to dance.",
    twoWord: "Want dance",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Dance",
      hi: "नृत्य",
      es: "Bailar",
      fr: "Danser",
      zh: "跳舞",
    },
  },
  {
    id: "sing",
    text: "Sing",
    message: "I want to sing.",
    twoWord: "Want sing",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Sing",
      hi: "गाना",
      es: "Cantar",
      fr: "Chanter",
      zh: "唱歌",
    },
  },
  {
    id: "draw",
    text: "Draw",
    message: "I want to draw.",
    twoWord: "Want draw",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Draw",
      hi: "चित्र बनाना",
      es: "Dibujar",
      fr: "Dessiner",
      zh: "画画",
    },
  },
  {
    id: "paint",
    text: "Paint",
    message: "I want to paint.",
    twoWord: "Want paint",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Paint",
      hi: "पेंट करना",
      es: "Pintar",
      fr: "Peindre",
      zh: "绘画",
    },
  },
  {
    id: "color",
    text: "Color",
    message: "I want to color.",
    twoWord: "Want color",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Color",
      hi: "रंग भरना",
      es: "Colorear",
      fr: "Colorier",
      zh: "涂色",
    },
  },
  {
    id: "swing",
    text: "Swing",
    message: "I want to swing.",
    twoWord: "Want swing",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Swing",
      hi: "झूला",
      es: "Columpio",
      fr: "Balançoire",
      zh: "秋千",
    },
  },
  {
    id: "slide",
    text: "Slide",
    message: "I want to slide.",
    twoWord: "Want slide",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Slide",
      hi: "स्लाइड",
      es: "Tobogán",
      fr: "Toboggan",
      zh: "滑梯",
    },
  },
  {
    id: "tv",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "TV",
      hi: "टीवी",
      es: "TV",
      fr: "TV",
      zh: "电视",
    },
  },
  {
    id: "tablet",
    text: "Tablet",
    message: "I want the tablet.",
    twoWord: "Want tablet",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Tablet",
      hi: "टैबलेट",
      es: "Tableta",
      fr: "Tablette",
      zh: "平板",
    },
  },
  {
    id: "puzzle",
    text: "Puzzle",
    message: "I want to do a puzzle.",
    twoWord: "Want puzzle",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Puzzle",
      hi: "पज़ल",
      es: "Rompecabezas",
      fr: "Puzzle",
      zh: "拼图",
    },
  },
  {
    id: "ride",
    text: "Ride",
    message: "I want to ride.",
    twoWord: "Want ride",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Ride",
      hi: "सवारी",
      es: "Montar",
      fr: "Monter",
      zh: "骑",
    },
  },
  {
    id: "run",
    text: "Run",
    message: "I want to run.",
    twoWord: "Want run",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Run",
      hi: "दौड़ना",
      es: "Correr",
      fr: "Courir",
      zh: "跑",
    },
  },
  {
    id: "jump",
    text: "Jump",
    message: "I want to jump.",
    twoWord: "Want jump",
    category: "play",
    color: "#2ECC71",
    translations: {
      en: "Jump",
      hi: "कूदना",
      es: "Saltar",
      fr: "Sauter",
      zh: "跳",
    },
  },
];
