import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const PLAY_VOCABULARY: ButtonTemplate[] = [
  // Basic Play
  {
    id: "play",
    text: "Play",
    message: "I want to play.",
    twoWord: "Want play",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("play"),
  },
  {
    id: "toy",
    text: "Toy",
    message: "I want a toy.",
    twoWord: "Want toy",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("toy"),
  },
  {
    id: "game",
    text: "Game",
    message: "I want to play a game.",
    twoWord: "Want game",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("game"),
  },
  {
    id: "ball",
    text: "Ball",
    message: "I want the ball.",
    twoWord: "Want ball",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("ball"),
  },
  {
    id: "doll",
    text: "Doll",
    message: "I want the doll.",
    twoWord: "Want doll",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("doll"),
  },
  {
    id: "blocks",
    text: "Blocks",
    message: "I want the blocks.",
    twoWord: "Want blocks",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("blocks"),
  },
  {
    id: "book",
    text: "Book",
    message: "I want to read a book.",
    twoWord: "Want book",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("book"),
  },
  {
    id: "music",
    text: "Music",
    message: "I want music.",
    twoWord: "Want music",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("music"),
  },
  {
    id: "dance",
    text: "Dance",
    message: "I want to dance.",
    twoWord: "Want dance",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("dance"),
  },
  {
    id: "sing",
    text: "Sing",
    message: "I want to sing.",
    twoWord: "Want sing",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("sing"),
  },
  {
    id: "draw",
    text: "Draw",
    message: "I want to draw.",
    twoWord: "Want draw",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("draw"),
  },
  {
    id: "paint",
    text: "Paint",
    message: "I want to paint.",
    twoWord: "Want paint",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("paint"),
  },
  {
    id: "color",
    text: "Color",
    message: "I want to color.",
    twoWord: "Want color",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("color"),
  },
  {
    id: "swing",
    text: "Swing",
    message: "I want to swing.",
    twoWord: "Want swing",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("swing"),
  },
  {
    id: "slide",
    text: "Slide",
    message: "I want to slide.",
    twoWord: "Want slide",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("slide"),
  },
  {
    id: "tv-play",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("tv"),
  },
  {
    id: "tablet-play",
    text: "Tablet",
    message: "I want the tablet.",
    twoWord: "Want tablet",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("tablet"),
  },
  {
    id: "puzzle",
    text: "Puzzle",
    message: "I want to do a puzzle.",
    twoWord: "Want puzzle",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("puzzle"),
  },
  {
    id: "ride",
    text: "Ride",
    message: "I want to ride.",
    twoWord: "Want ride",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("ride"),
  },
  {
    id: "run",
    text: "Run",
    message: "I want to run.",
    twoWord: "Want run",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("run"),
  },
  {
    id: "jump",
    text: "Jump",
    message: "I want to jump.",
    twoWord: "Want jump",
    category: "play",
    color: "#2ECC71",
    translations: getTranslationsForWord("jump"),
  },
];
