import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const PRONOUNS_VOCABULARY: ButtonTemplate[] = [
  {
    id: "I",
    text: "I",
    message: "I",
    twoWord: "I",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("I"),
  },
  {
    id: "me",
    text: "Me",
    message: "Me",
    twoWord: "Me",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("me"),
  },
  {
    id: "you",
    text: "You",
    message: "You",
    twoWord: "You",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("you"),
  },
  {
    id: "he",
    text: "He",
    message: "He",
    twoWord: "He",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("he"),
  },
  {
    id: "she",
    text: "She",
    message: "She",
    twoWord: "She",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("she"),
  },
  {
    id: "it",
    text: "It",
    message: "It",
    twoWord: "It",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("it"),
  },
  {
    id: "we",
    text: "We",
    message: "We",
    twoWord: "We",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("we"),
  },
  {
    id: "they",
    text: "They",
    message: "They",
    twoWord: "They",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("they"),
  },
  {
    id: "my",
    text: "My",
    message: "My",
    twoWord: "My",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("my"),
  },
  {
    id: "mine",
    text: "Mine",
    message: "Mine",
    twoWord: "Mine",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("mine"),
  },
  {
    id: "your",
    text: "Your",
    message: "Your",
    twoWord: "Your",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("your"),
  },
  {
    id: "our",
    text: "Our",
    message: "Our",
    twoWord: "Our",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("our"),
  },
  {
    id: "their",
    text: "Their",
    message: "Their",
    twoWord: "Their",
    category: "pronouns",
    color: "#FF8C42",
    translations: getTranslationsForWord("their"),
  },
];
