import { ButtonTemplate } from "../../types";

export const ROUTINES_VOCABULARY: ButtonTemplate[] = [
  // Basic Needs
  {
    id: "hungry",
    text: "Hungry",
    message: "I am hungry.",
    twoWord: "Am hungry",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Hungry",
      hi: "भूखा",
      es: "Hambriento",
      fr: "Affamé",
      zh: "饿了",
    },
  },
  {
    id: "thirsty",
    text: "Thirsty",
    message: "I am thirsty.",
    twoWord: "Am thirsty",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Thirsty",
      hi: "प्यासा",
      es: "Sediento",
      fr: "Assoiffé",
      zh: "渴了",
    },
  },
  {
    id: "sleepy",
    text: "Sleepy",
    message: "I am sleepy.",
    twoWord: "Am sleepy",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Sleepy",
      hi: "नींद आ रही",
      es: "Somnoliento",
      fr: "Somnolent",
      zh: "困了",
    },
  },
  {
    id: "bathroom-need",
    text: "Bathroom",
    message: "I need to go to the bathroom.",
    twoWord: "Need bathroom",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Bathroom",
      hi: "बाथरूम",
      es: "Baño",
      fr: "Toilettes",
      zh: "厕所",
    },
  },
  {
    id: "medicine",
    text: "Medicine",
    message: "I need medicine.",
    twoWord: "Need medicine",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Medicine",
      hi: "दवा",
      es: "Medicina",
      fr: "Médicament",
      zh: "药",
    },
  },
  {
    id: "pain",
    text: "Pain",
    message: "I have pain.",
    twoWord: "Have pain",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Pain",
      hi: "दर्द",
      es: "Dolor",
      fr: "Douleur",
      zh: "疼痛",
    },
  },
  {
    id: "hurt",
    text: "Hurt",
    message: "I am hurt.",
    twoWord: "Am hurt",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Hurt",
      hi: "चोट",
      es: "Herido",
      fr: "Blessé",
      zh: "受伤",
    },
  },
  {
    id: "help",
    text: "Help",
    message: "I need help.",
    twoWord: "Need help",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Help",
      hi: "मदद",
      es: "Ayuda",
      fr: "Aide",
      zh: "帮助",
    },
  },
  {
    id: "stop",
    text: "Stop",
    message: "Stop!",
    twoWord: "Stop",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Stop",
      hi: "रुको",
      es: "Para",
      fr: "Arrête",
      zh: "停止",
    },
  },
  {
    id: "wait",
    text: "Wait",
    message: "Wait.",
    twoWord: "Wait",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Wait",
      hi: "रुको",
      es: "Espera",
      fr: "Attends",
      zh: "等待",
    },
  },
  {
    id: "finished",
    text: "Finished",
    message: "I am finished.",
    twoWord: "Am finished",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Finished",
      hi: "खत्म",
      es: "Terminado",
      fr: "Terminé",
      zh: "完成了",
    },
  },
  {
    id: "again",
    text: "Again",
    message: "Again.",
    twoWord: "Again",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Again",
      hi: "फिर",
      es: "Otra vez",
      fr: "Encore",
      zh: "再次",
    },
  },
  {
    id: "more",
    text: "More",
    message: "More.",
    twoWord: "More",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "More",
      hi: "और",
      es: "Más",
      fr: "Plus",
      zh: "更多",
    },
  },
  {
    id: "enough",
    text: "Enough",
    message: "Enough.",
    twoWord: "Enough",
    category: "routines",
    color: "#E67E22",
    translations: {
      en: "Enough",
      hi: "बस",
      es: "Suficiente",
      fr: "Assez",
      zh: "够了",
    },
  },
];
