import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const ROUTINES_VOCABULARY: ButtonTemplate[] = [
  // Basic Needs
  {
    id: "hungry",
    text: "Hungry",
    message: "I am hungry.",
    twoWord: "Am hungry",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("hungry"),
  },
  {
    id: "thirsty",
    text: "Thirsty",
    message: "I am thirsty.",
    twoWord: "Am thirsty",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("thirsty"),
  },
  {
    id: "sleepy",
    text: "Sleepy",
    message: "I am sleepy.",
    twoWord: "Am sleepy",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("sleepy"),
  },
  {
    id: "sleep",
    text: "Sleep",
    message: "I want to sleep.",
    twoWord: "Want sleep",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("sleep"),
  },
  {
    id: "bathroom-need",
    text: "Bathroom",
    message: "I need to go to the bathroom.",
    twoWord: "Need bathroom",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("bathroom-need"),
  },
  {
    id: "medicine",
    text: "Medicine",
    message: "I need medicine.",
    twoWord: "Need medicine",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("medicine"),
  },
  {
    id: "pain",
    text: "Pain",
    message: "I have pain.",
    twoWord: "Have pain",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("pain"),
  },
  {
    id: "hurt",
    text: "Hurt",
    message: "I am hurt.",
    twoWord: "Am hurt",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("hurt"),
  },
  {
    id: "help",
    text: "Help",
    message: "I need help.",
    twoWord: "Need help",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("help"),
  },
  {
    id: "stop",
    text: "Stop",
    message: "Stop!",
    twoWord: "Stop",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("stop"),
  },
  {
    id: "wait",
    text: "Wait",
    message: "Wait.",
    twoWord: "Wait",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("wait"),
  },
  {
    id: "finished",
    text: "Finished",
    message: "I am finished.",
    twoWord: "Am finished",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("finished"),
  },
  {
    id: "again",
    text: "Again",
    message: "Again.",
    twoWord: "Again",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("again"),
  },
  {
    id: "more",
    text: "More",
    message: "More.",
    twoWord: "More",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("more"),
  },
  {
    id: "enough",
    text: "Enough",
    message: "Enough.",
    twoWord: "Enough",
    category: "routines",
    color: "#E67E22",
    translations: getTranslationsForWord("enough"),
  },
];
