import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const SCHOOL_VOCABULARY: ButtonTemplate[] = [
  // School Items
  {
    id: "teacher",
    text: "Teacher",
    message: "My teacher.",
    twoWord: "My teacher",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("teacher"),
  },
  {
    id: "student",
    text: "Student",
    message: "I am a student.",
    twoWord: "Am student",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("student"),
  },
  {
    id: "book-school",
    text: "Book",
    message: "I need a book.",
    twoWord: "Need book",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("book-school"),
  },
  {
    id: "paper",
    text: "Paper",
    message: "I need paper.",
    twoWord: "Need paper",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("paper"),
  },
  {
    id: "pencil",
    text: "Pencil",
    message: "I need a pencil.",
    twoWord: "Need pencil",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("pencil"),
  },
  {
    id: "pen",
    text: "Pen",
    message: "I need a pen.",
    twoWord: "Need pen",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("pen"),
  },
  {
    id: "eraser",
    text: "Eraser",
    message: "I need an eraser.",
    twoWord: "Need eraser",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("eraser"),
  },
  {
    id: "bag",
    text: "Bag",
    message: "I need my bag.",
    twoWord: "Need bag",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("bag"),
  },
  {
    id: "desk",
    text: "Desk",
    message: "I need a desk.",
    twoWord: "Need desk",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("desk"),
  },
  {
    id: "chair-school",
    text: "Chair",
    message: "I need a chair.",
    twoWord: "Need chair",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("chair-school"),
  },
  {
    id: "board",
    text: "Board",
    message: "I see the board.",
    twoWord: "See board",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("board"),
  },
  // School Actions
  {
    id: "read",
    text: "Read",
    message: "I want to read.",
    twoWord: "Want read",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("read"),
  },
  {
    id: "write",
    text: "Write",
    message: "I want to write.",
    twoWord: "Want write",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("write"),
  },
  {
    id: "draw-school",
    text: "Draw",
    message: "I want to draw.",
    twoWord: "Want draw",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("draw-school"),
  },
  {
    id: "cut",
    text: "Cut",
    message: "I want to cut.",
    twoWord: "Want cut",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("cut"),
  },
  {
    id: "glue",
    text: "Glue",
    message: "I want to glue.",
    twoWord: "Want glue",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("glue"),
  },
  {
    id: "count",
    text: "Count",
    message: "I want to count.",
    twoWord: "Want count",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("count"),
  },
  {
    id: "answer",
    text: "Answer",
    message: "I want to answer.",
    twoWord: "Want answer",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("answer"),
  },
  {
    id: "listen",
    text: "Listen",
    message: "I want to listen.",
    twoWord: "Want listen",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("listen"),
  },
  {
    id: "talk",
    text: "Talk",
    message: "I want to talk.",
    twoWord: "Want talk",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("talk"),
  },
  // Technology
  {
    id: "phone",
    text: "Phone",
    message: "I want the phone.",
    twoWord: "Want phone",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("phone"),
  },
  {
    id: "computer",
    text: "Computer",
    message: "I want the computer.",
    twoWord: "Want computer",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("computer"),
  },
  {
    id: "tablet-school",
    text: "Tablet",
    message: "I want the tablet.",
    twoWord: "Want tablet",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("tablet-school"),
  },
  {
    id: "tv-school",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("tv-school"),
  },
  {
    id: "internet",
    text: "Internet",
    message: "I want the internet.",
    twoWord: "Want internet",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("internet"),
  },
  {
    id: "video",
    text: "Video",
    message: "I want to watch a video.",
    twoWord: "Want video",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("video"),
  },
  {
    id: "game-school",
    text: "Game",
    message: "I want to play a game.",
    twoWord: "Want game",
    category: "school",
    color: "#16A085",
    translations: getTranslationsForWord("game-school"),
  },
];
