import { ButtonTemplate } from "../../types";

export const SCHOOL_VOCABULARY: ButtonTemplate[] = [
  // School Items
  {
    id: "teacher",
    text: "Teacher",
    message: "My teacher.",
    twoWord: "My teacher",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Teacher",
      hi: "शिक्षक",
      es: "Maestro",
      fr: "Enseignant",
      zh: "老师",
    },
  },
  {
    id: "student",
    text: "Student",
    message: "I am a student.",
    twoWord: "Am student",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Student",
      hi: "छात्र",
      es: "Estudiante",
      fr: "Étudiant",
      zh: "学生",
    },
  },
  {
    id: "book-school",
    text: "Book",
    message: "I need a book.",
    twoWord: "Need book",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Book",
      hi: "किताब",
      es: "Libro",
      fr: "Livre",
      zh: "书",
    },
  },
  {
    id: "paper",
    text: "Paper",
    message: "I need paper.",
    twoWord: "Need paper",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Paper",
      hi: "कागज",
      es: "Papel",
      fr: "Papier",
      zh: "纸",
    },
  },
  {
    id: "pencil",
    text: "Pencil",
    message: "I need a pencil.",
    twoWord: "Need pencil",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Pencil",
      hi: "पेंसिल",
      es: "Lápiz",
      fr: "Crayon",
      zh: "铅笔",
    },
  },
  {
    id: "pen",
    text: "Pen",
    message: "I need a pen.",
    twoWord: "Need pen",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Pen",
      hi: "कलम",
      es: "Bolígrafo",
      fr: "Stylo",
      zh: "钢笔",
    },
  },
  {
    id: "eraser",
    text: "Eraser",
    message: "I need an eraser.",
    twoWord: "Need eraser",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Eraser",
      hi: "रबर",
      es: "Borrador",
      fr: "Gomme",
      zh: "橡皮",
    },
  },
  {
    id: "bag",
    text: "Bag",
    message: "I need my bag.",
    twoWord: "Need bag",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Bag",
      hi: "बैग",
      es: "Bolsa",
      fr: "Sac",
      zh: "书包",
    },
  },
  {
    id: "desk",
    text: "Desk",
    message: "I need a desk.",
    twoWord: "Need desk",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Desk",
      hi: "डेस्क",
      es: "Escritorio",
      fr: "Bureau",
      zh: "桌子",
    },
  },
  {
    id: "chair-school",
    text: "Chair",
    message: "I need a chair.",
    twoWord: "Need chair",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Chair",
      hi: "कुर्सी",
      es: "Silla",
      fr: "Chaise",
      zh: "椅子",
    },
  },
  {
    id: "board",
    text: "Board",
    message: "I see the board.",
    twoWord: "See board",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Board",
      hi: "बोर्ड",
      es: "Pizarra",
      fr: "Tableau",
      zh: "黑板",
    },
  },
  // School Actions
  {
    id: "read",
    text: "Read",
    message: "I want to read.",
    twoWord: "Want read",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Read",
      hi: "पढ़ना",
      es: "Leer",
      fr: "Lire",
      zh: "读",
    },
  },
  {
    id: "write",
    text: "Write",
    message: "I want to write.",
    twoWord: "Want write",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Write",
      hi: "लिखना",
      es: "Escribir",
      fr: "Écrire",
      zh: "写",
    },
  },
  {
    id: "draw-school",
    text: "Draw",
    message: "I want to draw.",
    twoWord: "Want draw",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Draw",
      hi: "चित्र बनाना",
      es: "Dibujar",
      fr: "Dessiner",
      zh: "画画",
    },
  },
  {
    id: "cut",
    text: "Cut",
    message: "I want to cut.",
    twoWord: "Want cut",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Cut",
      hi: "काटना",
      es: "Cortar",
      fr: "Couper",
      zh: "剪",
    },
  },
  {
    id: "glue",
    text: "Glue",
    message: "I want to glue.",
    twoWord: "Want glue",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Glue",
      hi: "चिपकाना",
      es: "Pegar",
      fr: "Coller",
      zh: "粘",
    },
  },
  {
    id: "count",
    text: "Count",
    message: "I want to count.",
    twoWord: "Want count",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Count",
      hi: "गिनना",
      es: "Contar",
      fr: "Compter",
      zh: "数",
    },
  },
  {
    id: "answer",
    text: "Answer",
    message: "I want to answer.",
    twoWord: "Want answer",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Answer",
      hi: "जवाब",
      es: "Responder",
      fr: "Répondre",
      zh: "回答",
    },
  },
  {
    id: "listen",
    text: "Listen",
    message: "I want to listen.",
    twoWord: "Want listen",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Listen",
      hi: "सुनना",
      es: "Escuchar",
      fr: "Écouter",
      zh: "听",
    },
  },
  {
    id: "talk",
    text: "Talk",
    message: "I want to talk.",
    twoWord: "Want talk",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Talk",
      hi: "बात करना",
      es: "Hablar",
      fr: "Parler",
      zh: "说话",
    },
  },
  // Technology
  {
    id: "phone",
    text: "Phone",
    message: "I want the phone.",
    twoWord: "Want phone",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Phone",
      hi: "फोन",
      es: "Teléfono",
      fr: "Téléphone",
      zh: "电话",
    },
  },
  {
    id: "computer",
    text: "Computer",
    message: "I want the computer.",
    twoWord: "Want computer",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Computer",
      hi: "कंप्यूटर",
      es: "Computadora",
      fr: "Ordinateur",
      zh: "电脑",
    },
  },
  {
    id: "tablet-school",
    text: "Tablet",
    message: "I want the tablet.",
    twoWord: "Want tablet",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Tablet",
      hi: "टैबलेट",
      es: "Tableta",
      fr: "Tablette",
      zh: "平板",
    },
  },
  {
    id: "tv-school",
    text: "TV",
    message: "I want to watch TV.",
    twoWord: "Want TV",
    category: "school",
    color: "#16A085",
    translations: {
      en: "TV",
      hi: "टीवी",
      es: "TV",
      fr: "TV",
      zh: "电视",
    },
  },
  {
    id: "internet",
    text: "Internet",
    message: "I want the internet.",
    twoWord: "Want internet",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Internet",
      hi: "इंटरनेट",
      es: "Internet",
      fr: "Internet",
      zh: "互联网",
    },
  },
  {
    id: "video",
    text: "Video",
    message: "I want to watch a video.",
    twoWord: "Want video",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Video",
      hi: "वीडियो",
      es: "Video",
      fr: "Vidéo",
      zh: "视频",
    },
  },
  {
    id: "game-school",
    text: "Game",
    message: "I want to play a game.",
    twoWord: "Want game",
    category: "school",
    color: "#16A085",
    translations: {
      en: "Game",
      hi: "खेल",
      es: "Juego",
      fr: "Jeu",
      zh: "游戏",
    },
  },
];
