import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const SOCIAL_VOCABULARY: ButtonTemplate[] = [
  {
    id: "yes",
    text: "Yes",
    message: "Yes",
    twoWord: "Yes",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("yes"),
  },
  {
    id: "no",
    text: "No",
    message: "No",
    twoWord: "No",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("no"),
  },
  {
    id: "please",
    text: "Please",
    message: "Please",
    twoWord: "Please",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("please"),
  },
  {
    id: "thank-you",
    text: "Thank you",
    message: "Thank you",
    twoWord: "Thank you",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("thank-you"),
  },
  {
    id: "sorry",
    text: "Sorry",
    message: "Sorry",
    twoWord: "Sorry",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("sorry"),
  },
  {
    id: "hi",
    text: "Hi",
    message: "Hi",
    twoWord: "Hi",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("hi"),
  },
  {
    id: "hello",
    text: "Hello",
    message: "Hello",
    twoWord: "Hello",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("hello"),
  },
  {
    id: "goodbye",
    text: "Goodbye",
    message: "Goodbye",
    twoWord: "Goodbye",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("goodbye"),
  },
  {
    id: "okay",
    text: "Okay",
    message: "Okay",
    twoWord: "Okay",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("okay"),
  },
  {
    id: "wow",
    text: "Wow",
    message: "Wow",
    twoWord: "Wow",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("wow"),
  },
  {
    id: "cool",
    text: "Cool",
    message: "Cool",
    twoWord: "Cool",
    category: "social",
    color: "#E67E22",
    translations: getTranslationsForWord("cool"),
  },
];
