import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const VERBS_VOCABULARY: ButtonTemplate[] = [
  {
    id: "go",
    text: "Go",
    message: "Go",
    twoWord: "Go",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("go"),
  },
  {
    id: "stop",
    text: "Stop",
    message: "Stop",
    twoWord: "Stop",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("stop"),
  },
  {
    id: "want",
    text: "Want",
    message: "Want",
    twoWord: "Want",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("want"),
  },
  {
    id: "need",
    text: "Need",
    message: "Need",
    twoWord: "Need",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("need"),
  },
  {
    id: "like",
    text: "Like",
    message: "Like",
    twoWord: "Like",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("like"),
  },
  {
    id: "dont-like",
    text: "Don't like",
    message: "Don't like",
    twoWord: "Don't like",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("dont-like"),
  },
  {
    id: "play",
    text: "Play",
    message: "Play",
    twoWord: "Play",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("play"),
  },
  {
    id: "come",
    text: "Come",
    message: "Come",
    twoWord: "Come",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("come"),
  },
  {
    id: "give",
    text: "Give",
    message: "Give",
    twoWord: "Give",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("give"),
  },
  {
    id: "take",
    text: "Take",
    message: "Take",
    twoWord: "Take",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("take"),
  },
  {
    id: "do",
    text: "Do",
    message: "Do",
    twoWord: "Do",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("do"),
  },
  {
    id: "make",
    text: "Make",
    message: "Make",
    twoWord: "Make",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("make"),
  },
  {
    id: "eat",
    text: "Eat",
    message: "Eat",
    twoWord: "Eat",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("eat"),
  },
  {
    id: "drink",
    text: "Drink",
    message: "Drink",
    twoWord: "Drink",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("drink"),
  },
  {
    id: "look",
    text: "Look",
    message: "Look",
    twoWord: "Look",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("look"),
  },
  {
    id: "see",
    text: "See",
    message: "See",
    twoWord: "See",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("see"),
  },
  {
    id: "hear",
    text: "Hear",
    message: "Hear",
    twoWord: "Hear",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("hear"),
  },
  {
    id: "know",
    text: "Know",
    message: "Know",
    twoWord: "Know",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("know"),
  },
  {
    id: "think",
    text: "Think",
    message: "Think",
    twoWord: "Think",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("think"),
  },
  {
    id: "say",
    text: "Say",
    message: "Say",
    twoWord: "Say",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("say"),
  },
  {
    id: "tell",
    text: "Tell",
    message: "Tell",
    twoWord: "Tell",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("tell"),
  },
  {
    id: "feel",
    text: "Feel",
    message: "Feel",
    twoWord: "Feel",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("feel"),
  },
  {
    id: "use",
    text: "Use",
    message: "Use",
    twoWord: "Use",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("use"),
  },
  {
    id: "put",
    text: "Put",
    message: "Put",
    twoWord: "Put",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("put"),
  },
  {
    id: "help",
    text: "Help",
    message: "Help",
    twoWord: "Help",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("help"),
  },
  {
    id: "open",
    text: "Open",
    message: "Open",
    twoWord: "Open",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("open"),
  },
  {
    id: "close",
    text: "Close",
    message: "Close",
    twoWord: "Close",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("close"),
  },
  {
    id: "find",
    text: "Find",
    message: "Find",
    twoWord: "Find",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("find"),
  },
  {
    id: "show",
    text: "Show",
    message: "Show",
    twoWord: "Show",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("show"),
  },
  {
    id: "work",
    text: "Work",
    message: "Work",
    twoWord: "Work",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("work"),
  },
  {
    id: "start",
    text: "Start",
    message: "Start",
    twoWord: "Start",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("start"),
  },
  {
    id: "finish",
    text: "Finish",
    message: "Finish",
    twoWord: "Finish",
    category: "verbs",
    color: "#8E44AD",
    translations: getTranslationsForWord("finish"),
  },
];
