import { ButtonTemplate } from "../../types";
import { getTranslationsForWord } from "../translations";

export const WEATHER_VOCABULARY: ButtonTemplate[] = [
  {
    id: "sun",
    text: "Sun",
    message: "The sun is shining.",
    twoWord: "Sun shining",
    category: "weather",
    color: "#FFD700",
    translations: getTranslationsForWord("sun"),
  },
  {
    id: "rain",
    text: "Rain",
    message: "It is raining.",
    twoWord: "Is raining",
    category: "weather",
    color: "#87CEEB",
    translations: getTranslationsForWord("rain"),
  },
  {
    id: "cloud",
    text: "Cloud",
    message: "It is cloudy.",
    twoWord: "Is cloudy",
    category: "weather",
    color: "#B0C4DE",
    translations: getTranslationsForWord("cloud"),
  },
  {
    id: "snow",
    text: "Snow",
    message: "It is snowing.",
    twoWord: "Is snowy",
    category: "weather",
    color: "#F0F8FF",
    translations: getTranslationsForWord("snow"),
  },
  {
    id: "hot-weather",
    text: "Hot",
    message: "It is hot.",
    twoWord: "Is hot",
    category: "weather",
    color: "#FF6347",
    translations: getTranslationsForWord("hot-weather"),
  },
  {
    id: "cold-weather",
    text: "Cold",
    message: "It is cold.",
    twoWord: "Is cold",
    category: "weather",
    color: "#87CEEB",
    translations: getTranslationsForWord("cold-weather"),
  },
  {
    id: "windy",
    text: "Windy",
    message: "It is windy.",
    twoWord: "Is windy",
    category: "weather",
    color: "#D3D3D3",
    translations: getTranslationsForWord("windy"),
  },
  {
    id: "storm",
    text: "Storm",
    message: "There is a storm.",
    twoWord: "Is storm",
    category: "weather",
    color: "#696969",
    translations: getTranslationsForWord("storm"),
  },
  {
    id: "sunny",
    text: "Sunny",
    message: "It is sunny.",
    twoWord: "Is sunny",
    category: "weather",
    color: "#FFD700",
    translations: getTranslationsForWord("sunny"),
  },
  {
    id: "rainy",
    text: "Rainy",
    message: "It is rainy.",
    twoWord: "Is rainy",
    category: "weather",
    color: "#87CEEB",
    translations: getTranslationsForWord("rainy"),
  },
  {
    id: "snowy",
    text: "Snowy",
    message: "It is snowing.",
    twoWord: "Is snowy",
    category: "weather",
    color: "#F0F8FF",
    translations: getTranslationsForWord("snowy"),
  },
  {
    id: "cloudy",
    text: "Cloudy",
    message: "It is cloudy.",
    twoWord: "Is cloudy",
    category: "weather",
    color: "#B0C4DE",
    translations: getTranslationsForWord("cloudy"),
  },
];
