import { ButtonTemplate } from "../types";
import { getTranslationsForWord } from "./translations";

// Legacy BUTTON_TEMPLATES from the old system - keeping only unique items not covered in new categories
export const BUTTON_TEMPLATES: ButtonTemplate[] = [
  // Greetings
  {
    id: "hello",
    text: "Hello",
    message: "Hello!",
    category: "greetings",
    color: "#4ECDC4",
    translations: getTranslationsForWord("hello"),
  },
  {
    id: "goodbye",
    text: "Goodbye",
    message: "Goodbye!",
    category: "greetings",
    color: "#4ECDC4",
    translations: getTranslationsForWord("goodbye"),
  },
  {
    id: "thank-you",
    text: "Thank you",
    message: "Thank you!",
    category: "greetings",
    color: "#4ECDC4",
    translations: getTranslationsForWord("thank-you"),
  },
  {
    id: "please",
    text: "Please",
    message: "Please!",
    category: "greetings",
    color: "#4ECDC4",
    translations: getTranslationsForWord("please"),
  },
  {
    id: "happy-birthday",
    text: "Happy Birthday",
    message: "Happy Birthday!",
    category: "greetings",
    color: "#FF6B6B",
    translations: getTranslationsForWord("happy-birthday"),
  },
  {
    id: "i-love-you",
    text: "I love you",
    message: "I love you!",
    category: "greetings",
    color: "#FF6B6B",
    translations: getTranslationsForWord("i-love-you"),
  },

  // People
  {
    id: "mom",
    text: "Mom",
    message: "Mom!",
    twoWord: "Want mom",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("mom"),
  },
  {
    id: "dad",
    text: "Dad",
    message: "Dad!",
    twoWord: "Want dad",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("dad"),
  },
  {
    id: "friend",
    text: "Friend",
    message: "My friend.",
    twoWord: "My friend",
    category: "people",
    color: "#4ECDC4",
    translations: getTranslationsForWord("friend"),
  },

  // Places
  {
    id: "park",
    text: "Park",
    message: "I want to go to the park.",
    twoWord: "Want park",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("park"),
  },
  {
    id: "store",
    text: "Store",
    message: "I want to go to the store.",
    twoWord: "Want store",
    category: "places",
    color: "#3498DB",
    translations: getTranslationsForWord("store"),
  },

  // Weather
  {
    id: "sunny",
    text: "Sunny",
    message: "It is sunny.",
    twoWord: "Is sunny",
    category: "weather",
    color: "#F1C40F",
    translations: getTranslationsForWord("sunny"),
  },
  {
    id: "rainy",
    text: "Rainy",
    message: "It is rainy.",
    twoWord: "Is rainy",
    category: "weather",
    color: "#3498DB",
    translations: getTranslationsForWord("rainy"),
  },
  {
    id: "snowy",
    text: "Snowy",
    message: "It is snowing.",
    twoWord: "Is snowy",
    category: "weather",
    color: "#FFFFFF",
    translations: getTranslationsForWord("snowy"),
  },
  {
    id: "cloudy",
    text: "Cloudy",
    message: "It is cloudy.",
    twoWord: "Is cloudy",
    category: "weather",
    color: "#95A5A6",
    translations: getTranslationsForWord("cloudy"),
  },
  {
    id: "windy",
    text: "Windy",
    message: "It is windy.",
    twoWord: "Is windy",
    category: "weather",
    color: "#98D8C8",
    translations: getTranslationsForWord("windy"),
  },
];
